
package com.telus.cmb.jws;

import javax.xml.ws.WebFault;
import com.telus.tmi.xmlschema.xsd.common.exceptions.exceptions_v1_0.ServiceFaultInfo;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.3-06/19/2008 07:03 PM(bt)
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ServiceException", targetNamespace = "http://xmlschema.tmi.telus.com/xsd/common/exceptions/Exceptions_v1_0")
public class ServiceException extends Exception {

	private static final long serialVersionUID = 1L;
	
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceFaultInfo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServiceException(String message, ServiceFaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServiceException(String message, ServiceFaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.telus.tmi.xmlschema.xsd.common.exceptions.exceptions_v1_0.ServiceFaultInfo
     */
    public ServiceFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
