CREATE TABLE SOC_GROUP_EXT
(
GP_SOC CHAR(9 BYTE)  NOT NULL,
SOC CHAR(9 BYTE)  NOT NULL,
SYS_CREATION_DATE DATE NOT NULL,
SYS_UPDATE_DATE DATE,
OPERATOR_ID NUMBER(9),
APPLICATION_ID CHAR(6 BYTE),
DL_SERVICE_CODE CHAR(5 BYTE) NOT NULL,
DL_UPDATE_STAMP NUMBER(4)
);

CREATE INDEX SOC_GROUP_EXT_1IX ON SOC_GROUP_EXT
(SOC);

CREATE UNIQUE INDEX SOC_GROUP_EXT_PK ON SOC_GROUP_EXT
(GP_SOC, SOC);

ALTER TABLE SOC_GROUP_EXT ADD (
CONSTRAINT SOC_GROUP_EXT_PK PRIMARY KEY (GP_SOC, SOC)
USING INDEX );



