CREATE OR REPLACE SYNONYM NAME_GENERATION
  FOR TSDAPP01C.NAME_GENERATION
/

CREATE OR REPLACE SYNONYM ACCOUNT_TYPE
  FOR TSDAPP01C.ACCOUNT_TYPE
/

CREATE OR REPLACE SYNONYM CSM_ACTIVITY
  FOR TSDAPP01C.CSM_ACTIVITY
/

CREATE OR REPLACE SYNONYM CSM_STATUS_ACT
  FOR TSDAPP01C.CSM_STATUS_ACT
/

CREATE OR REPLACE SYNONYM AR_ACTIVITIES
  FOR TSDAPP01C.AR_ACTIVITIES
/

CREATE OR REPLACE SYNONYM ACTIVITY_RSN_TEXT
  FOR TSDAPP01C.ACTIVITY_RSN_TEXT
/

CREATE OR REPLACE SYNONYM CANCEL_REASON
  FOR TSDAPP01C.CANCEL_REASON
/

CREATE OR REPLACE SYNONYM ADJUSTMENT_REASON
  FOR TSDAPP01C.ADJUSTMENT_REASON
/

CREATE OR REPLACE SYNONYM STATE
  FOR TSDAPP01C.STATE
/

CREATE OR REPLACE SYNONYM NAME_TITLE
  FOR TSDAPP01C.NAME_TITLE
/

CREATE OR REPLACE SYNONYM HOLD_BILL_DEST
  FOR TSDAPP01C.HOLD_BILL_DEST
/

CREATE OR REPLACE SYNONYM COLLECTION_AGENCY
  FOR TSDAPP01C.COLLECTION_AGENCY
/

CREATE OR REPLACE SYNONYM COLLECTION_POL_STP
  FOR TSDAPP01C.COLLECTION_POL_STP
/

CREATE OR REPLACE SYNONYM FUNCTION
  FOR TSDAPP01C.FUNCTION
/

CREATE OR REPLACE SYNONYM FOREIGN_COUNTRY
  FOR TSDAPP01C.FOREIGN_COUNTRY
/

CREATE OR REPLACE SYNONYM PAYMENT_SUB_METHOD
  FOR TSDAPP01C.PAYMENT_SUB_METHOD
/

CREATE OR REPLACE SYNONYM DEPARTMENT
  FOR TSDAPP01C.DEPARTMENT
/

CREATE OR REPLACE SYNONYM PP_OC_RATE
  FOR TSDAPP01C.PP_OC_RATE
/

CREATE OR REPLACE SYNONYM FEATURE
  FOR TSDAPP01C.FEATURE
/

CREATE OR REPLACE SYNONYM CHARGE_INFO
  FOR TSDAPP01C.CHARGE_INFO
/

CREATE OR REPLACE SYNONYM N_DAP
  FOR TSDAPP01C.N_DAP
/

CREATE OR REPLACE SYNONYM PAYMENT_METHOD
  FOR TSDAPP01C.PAYMENT_METHOD
/

CREATE OR REPLACE SYNONYM PAYMENT_SOURCE
  FOR TSDAPP01C.PAYMENT_SOURCE
/

CREATE OR REPLACE SYNONYM PRODUCT
  FOR TSDAPP01C.PRODUCT
/

CREATE OR REPLACE SYNONYM PROVINCE
  FOR TSDAPP01C.PROVINCE
/

CREATE OR REPLACE SYNONYM SOC_SUBMKT_RELATION
  FOR TSDAPP01C.SOC_SUBMKT_RELATION
/

CREATE OR REPLACE SYNONYM SRV_STATUSES
  FOR TSDAPP01C.SRV_STATUSES
/

CREATE OR REPLACE SYNONYM GENERIC_CODES
  FOR TSDAPP01C.GENERIC_CODES
/

CREATE OR REPLACE SYNONYM SID
  FOR TSDAPP01C.SID
/

COMMIT;
