
/*******************************************************************************************
 WPS Fraud Rules setup for Mobility Sales System (12373DP)
/********************************************************************************************/

--step 1: create new application group
INSERT INTO APPLICATION_GROUP
(APP_GROUP_ID, APP_GROUP_CD, APP_GROUP_DESC, APP_GROUP_DESC_FR, LOAD_DT, UPDATE_DT, USER_LAST_MODIFY, TRANS_MODE_ID,PAYMENT_RULE_ID)
VALUES(
(select Max(APP_GROUP_ID)+1 from APPLICATION_GROUP),
'NGSP','Next Gen Sales Platform','Next Gen Sales Platform',SYSDATE,SYSDATE,'SYSTEM',
(SELECT TRANS_MODE_ID from TRANSACTION_MODE WHERE TRANS_MODE_TXT = 'E COMMERCE'),400039);

--step 2:  create new applicationId 
INSERT INTO APPLICATION
(APP_ID, APP_CD, APP_GROUP_ID, APP_DESC, APP_DESC_FR, LOAD_DT, UPDATE_DT, USER_LAST_MODIFY)
VALUES (
(SELECT Max(APP_ID)+1 from APPLICATION),'12373DP_1',
(SELECT APP_GROUP_ID from APPLICATION_GROUP WHERE APP_GROUP_CD = 'NGSP'),
'Mobility Sales System', 'Mobility Sales System', SYSDATE, SYSDATE, 'SYSTEM');

--step 3:  Global Payment Check Setup for Transaction_Type 'PURCHASE' and 'AUTHONLY'
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES (
(select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'AVS_GP'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES (
(select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'AVS_GP'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

--step 4: Trans Union AVS Check Setup for Transaction_Type 'PURCHASE' and 'AUTHONLY'
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES (
(select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'AVS_TU'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES (
(select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'AVS_TU'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

UPDATE FRAUD_CONFIG
SET FRAUD_CONFIG_TXT=CONCAT('12373DP,',FRAUD_CONFIG_TXT)
WHERE
FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'AVS_TU')
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'DEFAULT_MODE');

--step 5: International Check Setup for Transaction_Type 'PURCHASE' and 'AUTHONLY'
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'INT'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'INT'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

UPDATE FRAUD_CONFIG
SET FRAUD_CONFIG_TXT=CONCAT('12373DP,',FRAUD_CONFIG_TXT)
WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'INT')
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'ALTERNATE_MODE');

--step 6: Negative Check Setup for Transaction_Type 'PURCHASE' and 'AUTHONLY'
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'NEG'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'NEG'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

--step 7: Velocity Check Setup for Transaction_Type 'PURCHASE' and 'AUTHONLY'
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

UPDATE FRAUD_CONFIG
SET FRAUD_CONFIG_TXT=CONCAT('12373DP,',FRAUD_CONFIG_TXT)
WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'VEL')
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'ALTERNATE_MODE');