/**
 ROllback :  change the  Mobility Sales System ( NGSP) application Id back to  12373DP_1 and enable the velocity check
**/


-- step 1  the Application id changed back 12373DP_1

update application set app_cd = '12373DP_1' where app_cd = 'WSX_1';


-- step 2 enable  the velocity check for 12373DP_1  

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = '12373DP_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

UPDATE FRAUD_CONFIG
SET FRAUD_CONFIG_TXT=CONCAT('12373DP,',FRAUD_CONFIG_TXT)
WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'VEL')
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'ALTERNATE_MODE');

-- step 3 update FRAUD_CONFIG to replace WSX application Id.
 
UPDATE FRAUD_CONFIG SET FRAUD_CONFIG_TXT=REPLACE(FRAUD_CONFIG_TXT, 'WSX','12373DP') WHERE fraud_config_txt like  '%WSX%' ;

commit;




