
delete from APP_TRANSTYP_FRAUD_XREF where app_id = (select APP_ID from APPLICATION where APP_CD = 'EKW_3') 
and PYMT_TRANS_REASON_ID = (select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY')
and (FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'NEG')
or (FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'AVS_GP')));
