--step 1: Add Global Payment AVS Check Setup for Transaction_Type 'AUTHONLY'

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES (
(select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'EKW_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'AVS_GP'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

--step 2: Add Negative Check Setup for Transaction_Type 'AUTHONLY'

INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'EKW_3'),(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'NEG'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);
