UPDATE FRAUD_CONFIG SET FRAUD_CONFIG_TXT=REPLACE(FRAUD_CONFIG_TXT, 'EKW,', '')
WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'VEL') 
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'ALTERNATE_MODE');

UPDATE FRAUD_CONFIG SET FRAUD_CONFIG_TXT=CONCAT('EKW,',FRAUD_CONFIG_TXT)
WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'VEL') 
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'DEFAULT_MODE');
commit;