
/*******************************************************************************************
 WPS Fraud Rules setup for Enterprise Koodo Webstore (EKW)
/********************************************************************************************/

--step 1: create new application group
INSERT INTO APPLICATION_GROUP(APP_GROUP_ID, APP_GROUP_CD, APP_GROUP_DESC, APP_GROUP_DESC_FR, LOAD_DT, UPDATE_DT, USER_LAST_MODIFY, TRANS_MODE_ID,PAYMENT_RULE_ID)
VALUES((select Max(APP_GROUP_ID)+1 from APPLICATION_GROUP),'EKW','Koodo Webstore Checkout','Koodo Webstore Checkout',SYSDATE,SYSDATE,'SYSTEM', 
(SELECT TRANS_MODE_ID from TRANSACTION_MODE WHERE TRANS_MODE_TXT = 'RETAIL MANUAL KEYED'),400040);

--step 2:  create new applicationId 
INSERT INTO APPLICATION(APP_ID, APP_CD, APP_GROUP_ID, APP_DESC, APP_DESC_FR, LOAD_DT, UPDATE_DT, USER_LAST_MODIFY)
VALUES ((SELECT Max(APP_ID)+1 from APPLICATION),'EKW_3',(SELECT APP_GROUP_ID from APPLICATION_GROUP WHERE APP_GROUP_CD = 'EKW' ),
'Koodo Webstore Checkout', 'Koodo Webstore Checkout', SYSDATE, SYSDATE, 'SYSTEM');

--step 4:  Global Payment Check Setup for Transaction_Type 'PURCHASE'
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES (
(select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'EKW_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'AVS_GP'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

--step 5: CVV Check Setup for Transaction_Type 'PURCHASE'
INSERT INTO APP_TRANSTYP_FRAUD_XREF 
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'EKW_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'CVV'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

--step 6: CVV Check Setup for Transaction_Type 'AUTHONLY'
INSERT INTO APP_TRANSTYP_FRAUD_XREF 
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'EKW_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'CVV'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

-- step 7: International Check Setup:
UPDATE FRAUD_CONFIG SET FRAUD_CONFIG_TXT=CONCAT('EKW,',FRAUD_CONFIG_TXT)
WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'INT') 
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'ALTERNATE_MODE');

--step 8: Negative Check Setup for Transaction_Type 'PURCHASE'
INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'EKW_3'),(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'NEG'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

-- step 9: Velocity Check Setup for Transaction_Type 'PURCHASE' and 'AUTHONLY'
INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'EKW_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'EKW_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

UPDATE FRAUD_CONFIG SET FRAUD_CONFIG_TXT=CONCAT('EKW,',FRAUD_CONFIG_TXT)
WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'VEL') 
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'ALTERNATE_MODE');

commit;