/************************************************************************************************************************
  WPS Fraud Rules setup for  MSS / Next Gen Sales Platform Telus (NGSP_FB)   and  Koodo (NGSP_KD)
/*************************************************************************************************************************/
--step 1: create new application group and new applicationId for NGSP Telus and Koodo 

INSERT INTO APPLICATION_GROUP(APP_GROUP_ID, APP_GROUP_CD, APP_GROUP_DESC, APP_GROUP_DESC_FR, LOAD_DT, UPDATE_DT, USER_LAST_MODIFY, TRANS_MODE_ID,PAYMENT_RULE_ID)
VALUES((select Max(APP_GROUP_ID)+1 from APPLICATION_GROUP),'NGSP_FB','Next Gen Sales Platform','Next Gen Sales Platform',SYSDATE,SYSDATE,'SYSTEM', 
(SELECT TRANS_MODE_ID from TRANSACTION_MODE WHERE TRANS_MODE_TXT =  'E COMMERCE' ),4042);

INSERT INTO APPLICATION(APP_ID, APP_CD, APP_GROUP_ID, APP_DESC, APP_DESC_FR, LOAD_DT, UPDATE_DT, USER_LAST_MODIFY)
VALUES ((SELECT Max(APP_ID)+1 from APPLICATION),'QAZ_1',(SELECT APP_GROUP_ID from APPLICATION_GROUP WHERE APP_GROUP_CD = 'NGSP_FB' ),
'Mobility Sales System', 'Mobility Sales System', SYSDATE, SYSDATE, 'SYSTEM');  

INSERT INTO APPLICATION_GROUP(APP_GROUP_ID, APP_GROUP_CD, APP_GROUP_DESC, APP_GROUP_DESC_FR, LOAD_DT, UPDATE_DT, USER_LAST_MODIFY, TRANS_MODE_ID,PAYMENT_RULE_ID)
VALUES((select Max(APP_GROUP_ID)+1 from APPLICATION_GROUP),'NGSP_KD','Next Gen Sales Platform','Next Gen Sales Platform',SYSDATE,SYSDATE,'SYSTEM', 
(SELECT TRANS_MODE_ID from TRANSACTION_MODE WHERE TRANS_MODE_TXT =  'E COMMERCE' ),4041);

INSERT INTO APPLICATION(APP_ID, APP_CD, APP_GROUP_ID, APP_DESC, APP_DESC_FR, LOAD_DT, UPDATE_DT, USER_LAST_MODIFY)
VALUES ((SELECT Max(APP_ID)+1 from APPLICATION),'QAZ_3',(SELECT APP_GROUP_ID from APPLICATION_GROUP WHERE APP_GROUP_CD = 'NGSP_KD' ),
'Mobility Sales System', 'Mobility Sales System', SYSDATE, SYSDATE, 'SYSTEM');


--step 2 GP AVS Check Setup for Transaction Types 'PURCHASE' and AUTHONLY for MSS/NGSP Telus (QAZ_1) and Koodo (QAZ_3)

INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE 
where FRAUD_CHECK_TYPE_CD = 'AVS_GP'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE
where FRAUD_CHECK_TYPE_CD = 'AVS_GP'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);


INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE 
where FRAUD_CHECK_TYPE_CD = 'AVS_GP'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE
where FRAUD_CHECK_TYPE_CD = 'AVS_GP'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);


-- step 3 : International Check Setup for Transaction_Type 'PURCHASE' and AUTHONLY for MSS/NGSP Telus (QAZ_1) and Koodo (QAZ_3)

INSERT INTO APP_TRANSTYP_FRAUD_XREF(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_1'),(select PYMT_TRANS_REASON_ID from 
PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'INT'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);


INSERT INTO APP_TRANSTYP_FRAUD_XREF(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_1'),(select PYMT_TRANS_REASON_ID from
 PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'INT'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);
 
 
UPDATE FRAUD_CONFIG SET FRAUD_CONFIG_TXT=CONCAT('QAZ,',FRAUD_CONFIG_TXT) WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'INT')
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'ALTERNATE_MODE');


INSERT INTO APP_TRANSTYP_FRAUD_XREF(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_3'),(select PYMT_TRANS_REASON_ID from 
PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'INT'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);


INSERT INTO APP_TRANSTYP_FRAUD_XREF(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_3'),(select PYMT_TRANS_REASON_ID from
 PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'INT'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);
 



--step 4 : Negative Check Setup for Transaction_Type 'PURCHASE' and AUTHONLY for MSS/NGSP Telus (QAZ_1) and Koodo (QAZ_3)
INSERT INTO APP_TRANSTYP_FRAUD_XREF(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE 
where FRAUD_CHECK_TYPE_CD = 'NEG'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);


INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE 
where FRAUD_CHECK_TYPE_CD = 'NEG'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);


INSERT INTO APP_TRANSTYP_FRAUD_XREF(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE 
where FRAUD_CHECK_TYPE_CD = 'NEG'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);


INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS) 
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE 
where FRAUD_CHECK_TYPE_CD = 'NEG'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);



-- step 5 : Velocity Check Setup for Transaction_Type 'PURCHASE' and AUTHONLY for MSS/NGSP Telus (QAZ_1) and Koodo (QAZ_3)

INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_1'),(select PYMT_TRANS_REASON_ID from 
PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);


INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_1'),(select PYMT_TRANS_REASON_ID from 
PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

UPDATE FRAUD_CONFIG SET FRAUD_CONFIG_TXT=CONCAT('QAZ,',FRAUD_CONFIG_TXT)
WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'VEL')
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'ALTERNATE_MODE');

INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_3'),(select PYMT_TRANS_REASON_ID from 
PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);


INSERT INTO APP_TRANSTYP_FRAUD_XREF (APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),(select APP_ID from APPLICATION where APP_CD = 'QAZ_3'),(select PYMT_TRANS_REASON_ID from 
PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);



commit;

