
/*******************************************************************************************
 WPS Fraud Rules setup for Self Serve (SS_SVC)
/********************************************************************************************/

--step 1: create new applicationId 

INSERT INTO APPLICATION
(APP_ID, APP_CD, APP_GROUP_ID, APP_DESC, APP_DESC_FR, LOAD_DT, UPDATE_DT, USER_LAST_MODIFY)
VALUES (
(SELECT Max(APP_ID)+1 from APPLICATION),'SS_SVC_1',
(SELECT APP_GROUP_ID from APPLICATION_GROUP WHERE APP_GROUP_CD = 'SELF_SERVE'),
'Client Management Service', 'Service Client Management', SYSDATE, SYSDATE, 'SYSTEM');

INSERT INTO APPLICATION
(APP_ID, APP_CD, APP_GROUP_ID, APP_DESC, APP_DESC_FR, LOAD_DT, UPDATE_DT, USER_LAST_MODIFY)
VALUES (
(SELECT Max(APP_ID)+1 from APPLICATION),'SS_SVC_3',
(SELECT APP_GROUP_ID from APPLICATION_GROUP WHERE APP_GROUP_CD = 'SELF_SER_P'),
'Client Management Service', 'Service Client Management', SYSDATE, SYSDATE, 'SYSTEM');

--step 2: Trans Union AVS Check Setup for Transaction_Type 'PURCHASE' and 'AUTHONLY'

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES (
(select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'AVS_TU'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES (
(select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'AVS_TU'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);
 
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES (
(select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'AVS_TU'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES (
(select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'AVS_TU'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

UPDATE FRAUD_CONFIG
SET FRAUD_CONFIG_TXT=CONCAT('SS_SVC,',FRAUD_CONFIG_TXT)
WHERE
FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'AVS_TU')
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'ALTERNATE_MODE');

--step 3: CVV Check Setup for Transaction_Type 'PURCHASE' and 'AUTHONLY'

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'CVV'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'CVV'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);
 
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'CVV'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'CVV'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

--step 4: International Check Setup for Transaction_Type 'PURCHASE' and 'AUTHONLY'

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'INT'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);
 
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'INT'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE); 
 
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'INT'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'INT'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

UPDATE FRAUD_CONFIG
SET FRAUD_CONFIG_TXT=CONCAT('SS_SVC,',FRAUD_CONFIG_TXT)
WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'INT')
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'DEFAULT_MODE');

--step 5: Negative Check Setup for Transaction_Type 'PURCHASE' and 'AUTHONLY'

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'NEG'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'NEG'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);
 
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'NEG'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'AUTHONLY'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'NEG'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

--step 6: Velocity Check Setup for Transaction_Type 'PURCHASE' and 'AUTHONLY'

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_1'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'RETURN'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);
 
INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'PURCHASE'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

INSERT INTO APP_TRANSTYP_FRAUD_XREF
(APP_TRANSTYP_FRAUD_XREF_ID,APP_ID,PYMT_TRANS_REASON_ID,FRAUD_CHECK_TYPE_ID,CREATE_USER_ID,CREATE_TS,LAST_UPDATE_USER_ID,LAST_UPDT_TS)
VALUES ((select Max(APP_TRANSTYP_FRAUD_XREF_ID)+1 from APP_TRANSTYP_FRAUD_XREF),
(select APP_ID from APPLICATION where APP_CD = 'SS_SVC_3'),
(select PYMT_TRANS_REASON_ID from PYMT_TRANS_REASON where TRANS_REASON_DESC = 'RETURN'),
(select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE where FRAUD_CHECK_TYPE_CD = 'VEL'),
'SYSTEM',SYSDATE,'SYSTEM',SYSDATE);

UPDATE FRAUD_CONFIG
SET FRAUD_CONFIG_TXT=CONCAT('SS_SVC,',FRAUD_CONFIG_TXT)
WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'VEL')
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'ALTERNATE_MODE');