-- step 1: delete fraud rules setup for Application TERM2.
 
DELETE from APP_TRANSTYP_FRAUD_XREF 
WHERE APP_ID = (select APP_ID from APPLICATION where APP_CD = 'TERM2');

UPDATE FRAUD_CONFIG SET FRAUD_CONFIG_TXT=REPLACE(FRAUD_CONFIG_TXT, 'TERM2,','')
WHERE FRAUD_CHECK_TYPE_ID = (select FRAUD_CHECK_TYPE_ID from FRAUD_CHECK_TYPE WHERE FRAUD_CHECK_TYPE_CD = 'VEL') 
and FRAUD_CATEGORY_TYPE_ID = (select FRAUD_CATEGORY_TYPE_ID from FRAUD_CATEGORY_TYPE WHERE FRAUD_CATEGORY_TYPE_CD = 'DEFAULT_MODE');

commit;

