/* Generated by Together */

package com.telus.api.account;

import com.telus.api.*;

public class OutOfRangeMemberIdException extends TelusAPIException{

  private int minimumMemberInRange;

  private int maximunMemberInRange;


  public OutOfRangeMemberIdException(Throwable exception, int minimumMemberInRange, int maximunMemberInRange) {
  super(exception);
  this.minimumMemberInRange = minimumMemberInRange;
  this.maximunMemberInRange = maximunMemberInRange;
 }

 public OutOfRangeMemberIdException(String message, int minimumMemberInRange, int maximunMemberInRange) {
  super(message);
  this.minimumMemberInRange = minimumMemberInRange;
  this.maximunMemberInRange = maximunMemberInRange;
}

 public int getMinimumMemberInRange(){
   return minimumMemberInRange;
 }

 public int getMaximunMemberInRange(){
   return maximunMemberInRange;
 }

}
