/* Generated by Together */

package com.telus.api.account;

public interface SubscriptionRole
{
  String getCode();

  void setCode(String code);

  String getDealerCode();

  void setDealerCode(String dealerCode);

  String getSalesRepCode();

  void setSalesRepCode(String salesRepCode);

  String getCsrId();

  void setCsrId(String csrId);

  boolean isModified();
}
