/* Generated by Together */


package com.telus.api.reference;

import com.telus.api.*;

public interface CoverageRegion extends Reference {
  String getProvinceCode();
  String getType();
  String getFrequencyCode();

  public final static String COVERAGE_TYPE_EXTENDED = "EXTENDED";
  public final static String COVERAGE_TYPE_LOCAL    = "LOCAL";
  public final static String COVERAGE_TYPE_WIDE  = "WIDE";

  String[] getAssociatedServiceCodes();

  Service  getAssociatedService(PricePlan pricePlan) throws TelusAPIException ;
}
