/* Generated by Together */

package com.telus.api.reference;

public interface Reference extends java.io.Serializable{
    String getDescription();

    String getDescriptionFrench();

    String getCode();
}
