/* Generated by Together */

package com.telus.api.reference;
import java.util.Date;

public interface SubscriptionRoleType extends Reference
{
  public static final String SUBSCRIPTION_ROLE_ENTERPRISE = "ES";

  String getUserLastModify();

  Date getUpdateDate();

  Date getLoadDate();
}
