-- For AMDOCS_EXTO
GRANT EXECUTE ON ACC_ATTRIB_RETRIEVAL_PKG TO basread;
GRANT EXECUTE ON INVOICE_PKG TO basread;
GRANT EXECUTE ON ACC_RETRIEVAL_PKG TO basread;
GRANT EXECUTE ON CRDCHECK_RESULT_PKG TO basread;
GRANT EXECUTE ON subscriber_count_pkg TO basread;
GRANT EXECUTE ON sub_retrieval_pkg TO basread;
GRANT EXECUTE ON SUB_ATTRIB_RETRIEVAL_PKG TO basread;