--execute in amdocs_exto2
GRANT EXECUTE ON ACC_ATTRIB_RETRIEVAL_PKG TO basread2;
GRANT EXECUTE ON INVOICE_PKG TO basread2;
GRANT EXECUTE ON ACC_RETRIEVAL_PKG TO basread2;
GRANT EXECUTE ON CRDCHECK_RESULT_PKG TO basread2;
GRANT EXECUTE ON subscriber_count_pkg TO basread2;
GRANT EXECUTE ON sub_retrieval_pkg TO basread2;
GRANT EXECUTE ON SUB_ATTRIB_RETRIEVAL_PKG TO basread2;
