--execute in basread3
CREATE OR REPLACE SYNONYM ACC_ATTRIB_RETRIEVAL_PKG FOR amdocs_extd3.ACC_ATTRIB_RETRIEVAL_PKG;
CREATE OR REPLACE SYNONYM INVOICE_PKG FOR amdocs_extd3.INVOICE_PKG;
CREATE OR REPLACE SYNONYM ACC_RETRIEVAL_PKG FOR amdocs_extd3.ACC_RETRIEVAL_PKG;
CREATE OR REPLACE SYNONYM CRDCHECK_RESULT_PKG FOR amdocs_extd3.CRDCHECK_RESULT_PKG;
CREATE OR REPLACE SYNONYM subscriber_count_pkg FOR amdocs_extd3.subscriber_count_pkg;
CREATE OR REPLACE SYNONYM sub_retrieval_pkg FOR amdocs_extd3.sub_retrieval_pkg;
CREATE OR REPLACE SYNONYM sub_attrib_retrieval_pkg FOR amdocs_extd3.sub_attrib_retrieval_pkg;
