--execute in basread
CREATE OR REPLACE SYNONYM ACC_ATTRIB_RETRIEVAL_PKG FOR amdocs_exto.ACC_ATTRIB_RETRIEVAL_PKG;
CREATE OR REPLACE SYNONYM INVOICE_PKG FOR amdocs_exto.INVOICE_PKG;
CREATE OR REPLACE SYNONYM ACC_RETRIEVAL_PKG FOR amdocs_exto.ACC_RETRIEVAL_PKG;
CREATE OR REPLACE SYNONYM CRDCHECK_RESULT_PKG FOR amdocs_exto.CRDCHECK_RESULT_PKG;
CREATE OR REPLACE SYNONYM subscriber_count_pkg FOR amdocs_exto.subscriber_count_pkg;
CREATE OR REPLACE SYNONYM sub_retrieval_pkg FOR amdocs_exto.sub_retrieval_pkg;
CREATE OR REPLACE SYNONYM sub_attrib_retrieval_pkg FOR amdocs_exto.sub_attrib_retrieval_pkg;