/* Generated by Together */

package com.telus.eas.utility.info;
import com.telus.eas.framework.info.Info;
import com.telus.api.reference.AmountBarCode;

/**
 * Value object to contain all required details to generate barcodes for activation credits, promotion credits, and deposits.
 * @author Ken Duffy
 */
public class AmountBarCodeInfo extends Info implements AmountBarCode
{

  static final long serialVersionUID = 1L;

  public String getBarCode(){ return barCode; }

  public void setBarCode(String barCode){ this.barCode = barCode; }

  public String getBarCodeReason(){ return barCodeReason; }

  public void setBarCodeReason(String barCodeReason){ this.barCodeReason = barCodeReason; }

  public double getAmount(){ return amount; }

  public void setAmount(double amount){ this.amount = amount; }

  public void setDescription(String description) {this.description=description; }

  public void setDescriptionFrench(String descriptionFrench) {this.descriptionFrench=descriptionFrench;}

  public void setCode(String code) {this.code=code;}

  public String getDescription()
  {
    return getBarCodeReason();
  }

  public String getDescriptionFrench()
  {
    return descriptionFrench;
  }

  public String getCode()
  {
    return code;
  }

  public String toString()
  {
    StringBuffer s = new StringBuffer(128);
    s.append("AmountBarCodeInfo:[\n");
    s.append("    amount=[").append(amount).append("]\n");
    s.append("    barcode=[").append(barCode).append("]\n");
    s.append("    barcodeReason=[").append(barCodeReason).append("]\n");
    s.append("    code=[").append(code).append("]\n");
    s.append("    description=[").append(description).append("]\n");
    s.append("    descriptionFrench=[").append(descriptionFrench).append(
        "]\n");
    s.append("]");
    return s.toString();
  }

  private String description;
  private String descriptionFrench;
  private String code;
  private String barCode;
  private String barCodeReason;
  private double amount;
}
