-- INSERTING into ACCOUNT_SUB_TYPE_DEFAULTS

Insert into ACCOUNT_SUB_TYPE_DEFAULTS (ACCT_TYPE,ACCT_SUB_TYPE,NL_ID,DEFAULT_DEALER,DEFAULT_SALES_CODE) values ('B','A','TLS','A001000001','0000');

Insert into ACCOUNT_SUB_TYPE_DEFAULTS (ACCT_TYPE,ACCT_SUB_TYPE,NL_ID,DEFAULT_DEALER,DEFAULT_SALES_CODE) values ('B','N','TLS','A001000001','0000');

Insert into ACCOUNT_SUB_TYPE_DEFAULTS (ACCT_TYPE,ACCT_SUB_TYPE,NL_ID,DEFAULT_DEALER,DEFAULT_SALES_CODE) values ('C','Y','TLS','A001000001','0000');

-- INSERTING into ACCT_TYPE_NUMBER_LOCATIONS

INSERT INTO ACCT_TYPE_NUMBER_LOCATIONS (acct_type, acct_sub_type, number_location_id, dealer, sales_code)
VALUES('B','A','TLS','A001000001','0000');

INSERT INTO ACCT_TYPE_NUMBER_LOCATIONS (acct_type, acct_sub_type, number_location_id, dealer, sales_code)
VALUES('B','N','TLS','A001000001','0000');

INSERT INTO ACCT_TYPE_NUMBER_LOCATIONS (acct_type, acct_sub_type, number_location_id, dealer, sales_code)
VALUES('C','Y','TLS','A001000001','0000');

commit;
