-- Creating the group
INSERT INTO TGROUP ( GROUP_ID, GROUP_CD, GROUP_NM, GROUP_DESCRIPTION, CREATE_TS, CREATE_USER_ID,
LAST_UPDATE_TS, LAST_UPDATE_USER_ID, APPLICATION_NM, EFFECTIVE_START_TS, EFFECTIVE_END_TS,
DATA_SRC_ID ) VALUES ( 
seq_tgroup.nextval, 'CSRDESKTOP', 'CSR Desktop', 'Call Centre Agent Group - used to assign agent application permissions', sysdate, 'x108373', sysdate
, 'x108373', 'TBS Pricing', sysdate, TO_TIMESTAMP('12/31/9999 12:00:00.000000 AM','MM/DD/YYYY fmHH12fm:MI:SS.FF AM')
, NULL); 
COMMIT;

-- Creating  role
INSERT INTO ROLE ( ROLE_ID, ROLE_CD, ROLE_NM, ROLE_DESC, CREATE_TS, CREATE_USER_ID, LAST_UPDATE_TS,
LAST_UPDATE_USER_ID, APPLICATION_NM, EFFECTIVE_START_TS, EFFECTIVE_END_TS,
DATA_SRC_ID ) VALUES ( 
seq_role.nextval, 'EEAGENT_SD', 'EE Agent - Smart Desktop', 'Enterprise Experience Agent for Smart Desktop', sysdate, 'x108373', sysdate, 'x108373', 'Smart Desktop', sysdate, 
TO_TIMESTAMP('12/31/9999 12:00:00.000000 AM','MM/DD/YYYY fmHH12fm:MI:SS.FF AM'), 401); 
COMMIT;

-- Creating  role
INSERT INTO ROLE ( ROLE_ID, ROLE_CD, ROLE_NM, ROLE_DESC, CREATE_TS, CREATE_USER_ID, LAST_UPDATE_TS,
LAST_UPDATE_USER_ID, APPLICATION_NM, EFFECTIVE_START_TS, EFFECTIVE_END_TS,
DATA_SRC_ID ) VALUES ( 
seq_role.nextval, 'EEAGENT_OOM', 'EE Agent - OOM', 'Enterprise Experience Agent for Online Offer Manager', sysdate, 'x108373', sysdate, 'x108373', 'OOM', sysdate, 
TO_TIMESTAMP('12/31/9999 12:00:00.000000 AM','MM/DD/YYYY fmHH12fm:MI:SS.FF AM'), 401); 
COMMIT;

-- Creating  role
INSERT INTO ROLE ( ROLE_ID, ROLE_CD, ROLE_NM, ROLE_DESC, CREATE_TS, CREATE_USER_ID, LAST_UPDATE_TS,
LAST_UPDATE_USER_ID, APPLICATION_NM, EFFECTIVE_START_TS, EFFECTIVE_END_TS,
DATA_SRC_ID ) VALUES ( 
seq_role.nextval, 'EEAGENT_MERCURY', 'EE Agent - Mercury', 'Enterprise Experience Agent for Mercury', sysdate, 'x108373', sysdate, 'x108373', 'Mercury', sysdate, 
TO_TIMESTAMP('12/31/9999 12:00:00.000000 AM','MM/DD/YYYY fmHH12fm:MI:SS.FF AM'), 401); 
COMMIT;

-- Creating an association
INSERT INTO GROUP_ROLE ( GROUP_ROLE_ID, ROLE_ID, GROUP_ID, CREATE_TS, CREATE_USER_ID,
LAST_UPDATE_TS, LAST_UPDATE_USER_ID, EFFECTIVE_END_TS, EFFECTIVE_START_TS,
DATA_SRC_ID ) VALUES ( 
seq_group_role.nextval, (select ROLE_ID from ROLE where ROLE_CD = 'EEAGENT_SD'), (select GROUP_ID from TGROUP where GROUP_CD = 'CSRDESKTOP'), sysdate, 'x108373', sysdate, 'x108373', TO_TIMESTAMP('12/31/9999 12:00:00.000000 AM','MM/DD/YYYY fmHH12fm:MI:SS.FF AM')
, sysdate, 401);  

-- Creating an association
INSERT INTO GROUP_ROLE ( GROUP_ROLE_ID, ROLE_ID, GROUP_ID, CREATE_TS, CREATE_USER_ID,
LAST_UPDATE_TS, LAST_UPDATE_USER_ID, EFFECTIVE_END_TS, EFFECTIVE_START_TS,
DATA_SRC_ID ) VALUES ( 
seq_group_role.nextval, (select ROLE_ID from ROLE where ROLE_CD = 'EEAGENT_OOM'), (select GROUP_ID from TGROUP where GROUP_CD = 'CSRDESKTOP'), sysdate, 'x108373', sysdate, 'x108373', TO_TIMESTAMP('12/31/9999 12:00:00.000000 AM','MM/DD/YYYY fmHH12fm:MI:SS.FF AM')
, sysdate, 401);  

-- Creating an association
INSERT INTO GROUP_ROLE ( GROUP_ROLE_ID, ROLE_ID, GROUP_ID, CREATE_TS, CREATE_USER_ID,
LAST_UPDATE_TS, LAST_UPDATE_USER_ID, EFFECTIVE_END_TS, EFFECTIVE_START_TS,
DATA_SRC_ID ) VALUES ( 
seq_group_role.nextval, (select ROLE_ID from ROLE where ROLE_CD = 'EEAGENT_MERCURY'), (select GROUP_ID from TGROUP where GROUP_CD = 'CSRDESKTOP'), sysdate, 'x108373', sysdate, 'x108373', TO_TIMESTAMP('12/31/9999 12:00:00.000000 AM','MM/DD/YYYY fmHH12fm:MI:SS.FF AM')
, sysdate, 401);  

COMMIT;
