


CREATE TABLE CONEADM.ALLOWED_CONT_EVENT_MECH (
       CONTACT_EVENT_TYPE_ID NUMBER(38) NOT NULL,
       CONTACT_MECHANISM_ID NUMBER(38) NOT NULL,
       DATABASE_NAME        VARCHAR2(60) NULL,
       TABLE_NAME           VARCHAR2(60) NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
    	 TABLESPACE data01
 ;


ALTER TABLE CONEADM.ALLOWED_CONT_EVENT_MECH
       ADD  ( CONSTRAINT PK_ALLOWED_CONT_EVENT_MECH PRIMARY KEY (
              CONTACT_EVENT_TYPE_ID, CONTACT_MECHANISM_ID)
       USING INDEX
    	 TABLESPACE index01 ) ;



CREATE TABLE CONEADM.ALLOWED_CONTENT_MECHANISM (
       CONTACT_CONTENT_TYPE_ID NUMBER(38) NOT NULL,
       CONTACT_EVENT_TYPE_ID NUMBER(38) NOT NULL,
       CONTACT_MECHANISM_ID NUMBER(38) NOT NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
    	 TABLESPACE data01
 ;


ALTER TABLE CONEADM.ALLOWED_CONTENT_MECHANISM
       ADD  ( CONSTRAINT PK_ALLOWED_CONTENT_MECHANISM PRIMARY KEY (
              CONTACT_CONTENT_TYPE_ID, CONTACT_EVENT_TYPE_ID, 
              CONTACT_MECHANISM_ID)
       USING INDEX
    	 TABLESPACE index01 ) ;


CREATE TABLE CONEADM.CLIENT_CONTACT_EVENT (
       CONTACT_EVENT_ID     NUMBER(38) NOT NULL,
       CONTACT_EVENT_TYPE_ID NUMBER(38) NOT NULL,
       CLIENT_ID            NUMBER NOT NULL,
       CONTACT_EVENT_STATUS_CODE VARCHAR2(1) NOT NULL,
       STATUS_TIMESTAMP     DATE NOT NULL,
       LOAD_DT              DATE NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
PARTITION BY RANGE (contact_event_id)
   SUBPARTITION BY LIST (contact_event_type_id)
      SUBPARTITION TEMPLATE
         (SUBPARTITION SMS  VALUES (1), 
    	 SUBPARTITION other VALUES (DEFAULT))
      (PARTITION contact_20000 VALUES LESS THAN (20001),
       PARTITION contact_MAX VALUES LESS THAN (MAXVALUE))  
	TABLESPACE DATA02;


ALTER TABLE CONEADM.CLIENT_CONTACT_EVENT
       ADD  ( CONSTRAINT PK_CLIENT_CONTACT_EVENT PRIMARY KEY (
              CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID, CLIENT_ID)
       USING INDEX
    	 TABLESPACE INDEX02  local) ;

 CREATE TABLE CONEADM.CONTACT_CONTENT_LANGUAGE (
        CONTACT_CONTENT_TYPE_ID NUMBER(38) NOT NULL,
        LANGUAGE_CD          VARCHAR2(2) NOT NULL,
        TEMPLATE_TEXT        VARCHAR2(2000) NULL,
        LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
        UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
        USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
 )
        TABLESPACE DATA01
  ;

ALTER TABLE CONEADM.CONTACT_CONTENT_LANGUAGE
       ADD  ( CONSTRAINT PK_CONTACT_CONTENT_LANGUAGE PRIMARY KEY (
              CONTACT_CONTENT_TYPE_ID, LANGUAGE_CD)
       USING INDEX
       TABLESPACE INDEX01 ) ;  

CREATE TABLE CONEADM.CONTACT_CONTENT_PARAM_TYPE (
       CONTACT_CONTENT_TYPE_ID NUMBER(38) NOT NULL,
       CONTACT_CONTENT_PARAM_NO NUMBER(22) NOT NULL,
       DESCRIPTION_FRENCH   VARCHAR2(100) NULL,
       DESCRIPTION          VARCHAR2(100) NOT NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
    	 TABLESPACE data01
 ;


ALTER TABLE CONEADM.CONTACT_CONTENT_PARAM_TYPE
       ADD  ( CONSTRAINT PK_CONTACT_CONTENT_PARAM_TYPE PRIMARY KEY (
              CONTACT_CONTENT_TYPE_ID, CONTACT_CONTENT_PARAM_NO)
       USING INDEX
    	 TABLESPACE index01 ) ;



CREATE TABLE CONEADM.CONTACT_CONTENT_TYPE (
       CONTACT_CONTENT_TYPE_ID NUMBER(38) NOT NULL,
       DESCRIPTION          VARCHAR2(100) NOT NULL,
       DESCRIPTION_FRENCH   VARCHAR2(100) NULL,
       BILLABLE_INDICATOR   VARCHAR2(1) DEFAULT 'N' NOT NULL,
       ORIGINATING_USER_NAME VARCHAR2(60) NULL,
       REPLY_TO_NAME        VARCHAR2(60) NULL,
       DELIVERY_RECEIPT_REQ_IND VARCHAR2(1) NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
    	 TABLESPACE data01
 ;


ALTER TABLE CONEADM.CONTACT_CONTENT_TYPE
       ADD  ( CONSTRAINT PK_CONTACT_CONTENT_TYPE PRIMARY KEY (
              CONTACT_CONTENT_TYPE_ID)
       USING INDEX
    	 TABLESPACE index01 ) ;


CREATE TABLE CONEADM.CONTACT_EVENT (
       CONTACT_EVENT_ID     NUMBER(38) NOT NULL,
       CONTACT_EVENT_TYPE_ID NUMBER(38) NOT NULL,
       START_TIMESTAMP      DATE NOT NULL,
       END_TIMESTAMP        DATE NULL,
       TEAM_MEMBER_ID       NUMBER(22) NULL,
       CONTACT_EVENT_STATUS_CODE VARCHAR2(1) NOT NULL,
       STATUS_TIMESTAMP     DATE NOT NULL,
       COMMENTS             VARCHAR2(2000) NULL,
       CONTACT_MECHANISM_ID NUMBER(38) NOT NULL,
       CONTACT_CONTENT_TYPE_ID NUMBER(38) NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL,
       CHNL_ORG_ID          NUMBER(22) NULL,
       BP_GROUP_CD          VARCHAR2(10) NULL,
       STATUS_CONFIRMED_IND VARCHAR2(1) DEFAULT 'N' NULL,
       PROCESSING_SW_APPLICATION_ID NUMBER(38) NULL,
       ASSOCIATED_CONTACT_EVENT_ID NUMBER(38) NULL
)
PARTITION BY RANGE (contact_event_id)
   SUBPARTITION BY LIST (contact_event_type_id)
      SUBPARTITION TEMPLATE
         (SUBPARTITION SMS  VALUES (1),
         SUBPARTITION other VALUES (DEFAULT))
      (PARTITION contact_20000 VALUES LESS THAN (20001),
       PARTITION contact_MAX VALUES LESS THAN (MAXVALUE))
        TABLESPACE DATA02
 ;


ALTER TABLE CONEADM.CONTACT_EVENT
       ADD  ( CONSTRAINT PK_CONTACT_EVENT PRIMARY KEY (
              CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID)
       USING INDEX
    	 TABLESPACE INDEX02 local ) ;


CREATE TABLE CONEADM.CONTACT_EVENT_PURPOSE (
       CONTACT_EVENT_ID     NUMBER(38) NOT NULL,
       CONTACT_EVENT_TYPE_ID NUMBER(38) NOT NULL,
       CONTACT_EVENT_PURPOSE_TYPE_ID NUMBER(38) NOT NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
PARTITION BY RANGE (contact_event_id)
   SUBPARTITION BY LIST (contact_event_type_id)
      SUBPARTITION TEMPLATE
         (SUBPARTITION SMS  VALUES (1),
         SUBPARTITION other VALUES (DEFAULT))
      (PARTITION contact_20000 VALUES LESS THAN (20001),
       PARTITION contact_MAX VALUES LESS THAN (MAXVALUE))
    	 TABLESPACE DATA02;


ALTER TABLE CONEADM.CONTACT_EVENT_PURPOSE
       ADD  ( CONSTRAINT PK_CONTACT_EVENT_PURPOSE PRIMARY KEY (
              CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID, 
              CONTACT_EVENT_PURPOSE_TYPE_ID)
       USING INDEX
    	 TABLESPACE INDEX02 local) ;

CREATE TABLE CONEADM.CONTACT_EVENT_PURPOSE_TYPE (
       CONTACT_EVENT_PURPOSE_TYPE_ID NUMBER(38) NOT NULL,
       DESCRIPTION          VARCHAR2(100) NOT NULL,
       DESCRIPTION_FRENCH   VARCHAR2(100) NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
    	 TABLESPACE data01
 ;


ALTER TABLE CONEADM.CONTACT_EVENT_PURPOSE_TYPE
       ADD  ( CONSTRAINT PK_CONTACT_EVENT_PURPOSE_TYPE PRIMARY KEY (
              CONTACT_EVENT_PURPOSE_TYPE_ID)
       USING INDEX
    	 TABLESPACE index01 ) ;



CREATE TABLE CONEADM.CONTACT_EVENT_STATUS_TYPE (
       CONTACT_EVENT_STATUS_CD VARCHAR2(1) NOT NULL,
       DESCRIPTION          VARCHAR2(100) NOT NULL,
       DESCRIPTION_FRENCH   VARCHAR2(100) NULL,
       LOAD_DT              DATE NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
    	 TABLESPACE data01
 ;


ALTER TABLE CONEADM.CONTACT_EVENT_STATUS_TYPE
       ADD  ( CONSTRAINT PK_CONTACT_EVENT_STATUS_TYPE PRIMARY KEY (
              CONTACT_EVENT_STATUS_CD)
       USING INDEX
    	 TABLESPACE index01 ) ;

CREATE PUBLIC SYNONYM CONTACT_EVENT_STATUS_TYPE FOR CONEADM.CONTACT_EVENT_STATUS_TYPE;


CREATE TABLE CONEADM.CONTACT_EVENT_TYPE (
       CONTACT_EVENT_TYPE_ID NUMBER(38) NOT NULL,
       DESCRIPTION          VARCHAR2(100) NOT NULL,
       DESCRIPTION_FRENCH   VARCHAR2(100) NULL,
       OUTBOUND_INDICATOR   VARCHAR2(1) DEFAULT 'N' NOT NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
    	 TABLESPACE data01
 ;


ALTER TABLE CONEADM.CONTACT_EVENT_TYPE
       ADD  ( CONSTRAINT PK_CONTACT_EVENT_TYPE PRIMARY KEY (
              CONTACT_EVENT_TYPE_ID)
       USING INDEX
    	 TABLESPACE index01 ) ;




CREATE TABLE CONEADM.CONTACT_EVNT_CONTENT_PARAM (
       CONTACT_EVENT_ID     NUMBER(38) NOT NULL,
       CONTACT_EVENT_TYPE_ID NUMBER(38) NOT NULL,
       CONTACT_CONTENT_TYPE_ID NUMBER(38) NOT NULL,
       CONTACT_CONTENT_PARAM_NO NUMBER(22) NOT NULL,
       PARAMETER_VALUE      VARCHAR2(100) NOT NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
PARTITION BY RANGE (contact_event_id)
   SUBPARTITION BY LIST (contact_event_type_id)
      SUBPARTITION TEMPLATE
         (SUBPARTITION SMS  VALUES (1),
         SUBPARTITION other VALUES (DEFAULT))
      (PARTITION contact_20000 VALUES LESS THAN (20001),
       PARTITION contact_MAX VALUES LESS THAN (MAXVALUE))
        TABLESPACE DATA02
 ;


ALTER TABLE CONEADM.CONTACT_EVNT_CONTENT_PARAM
       ADD  ( CONSTRAINT PK_CONTACT_EVNT_CONTENT_PARAM PRIMARY KEY (
              CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID, 
              CONTACT_CONTENT_TYPE_ID, CONTACT_CONTENT_PARAM_NO)
       USING INDEX
    	 TABLESPACE INDEX02 local ) ;

CREATE TABLE CONEADM.CONTACT_MECHANISM_TYPE (
       CONTACT_MECHANISM_ID NUMBER(38) NOT NULL,
       DESCRIPTION          VARCHAR2(100) NOT NULL,
       DESCRIPTION_FRENCH   VARCHAR2(100) NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
    	 TABLESPACE data01
 ;


ALTER TABLE CONEADM.CONTACT_MECHANISM_TYPE
       ADD  ( CONSTRAINT PK_CONTACT_MECHANISM_TYPE PRIMARY KEY (
              CONTACT_MECHANISM_ID)
       USING INDEX
    	 TABLESPACE index01 ) ;


CREATE TABLE CONEADM.INDIVIDUAL_CONTACT_EVENT (
       CONTACT_EVENT_ID     NUMBER(38) NOT NULL,
       CONTACT_EVENT_TYPE_ID NUMBER(38) NOT NULL,
       INDIVIDUAL_ID        NUMBER NOT NULL,
       CONTACT_EVENT_STATUS_CODE VARCHAR2(1) NOT NULL,
       STATUS_TIMESTAMP     DATE NOT NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
PARTITION BY RANGE (contact_event_id)
   SUBPARTITION BY LIST (contact_event_type_id)
      SUBPARTITION TEMPLATE
         (SUBPARTITION SMS  VALUES (1),
         SUBPARTITION other VALUES (DEFAULT))
      (PARTITION contact_20000 VALUES LESS THAN (20001),
       PARTITION contact_MAX VALUES LESS THAN (MAXVALUE))
        TABLESPACE DATA02
 ;


ALTER TABLE CONEADM.INDIVIDUAL_CONTACT_EVENT
       ADD  ( CONSTRAINT PK_INDIVIDUAL_CONTACT_EVENT PRIMARY KEY (
              CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID, INDIVIDUAL_ID)
       USING INDEX
    	 TABLESPACE INDEX02 local ) ;


CREATE TABLE CONEADM.SMS_CLIENT_NOTIFICATION (
       CONTACT_EVENT_ID     NUMBER(38) NOT NULL,
       CONTACT_EVENT_TYPE_ID NUMBER(38) NOT NULL,
       KB_SUBSCRIBER_NO     VARCHAR(20) NOT NULL,
       KB_PRODUCT_TYPE      VARCHAR(1) NOT NULL,
       KB_BAN               NUMBER(9) NOT NULL,
       SCHEDULED_DELIVERY_DATETIME DATE NULL,
       PRIORITY_NUMBER      NUMBER(3) NULL,
       TIME_TO_LIVE         NUMBER(9) NULL,
       DELIVERY_RECEIPT_REQ_IND VARCHAR2(1) DEFAULT 'Y' NOT NULL,
       BILLABLE_INDICATOR   VARCHAR2(1) DEFAULT 'Y' NOT NULL,
       ORIGINATING_USER_NAME VARCHAR2(60) NULL,
       MESSAGE_TEXT         VARCHAR2(2000) NOT NULL,
       SMS_GATEWAY_MESSAGE_ID NUMBER(38) NULL,
       SMS_STATUS_TYPE_CD   VARCHAR2(20) NOT NULL,
       STATUS_REASON_CODE   VARCHAR2(10) NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL,
       DESTINATION_PHONE_NO VARCHAR(20) NULL
)
PARTITION BY RANGE (contact_event_id)
   SUBPARTITION BY LIST (contact_event_type_id)
      SUBPARTITION TEMPLATE
         (SUBPARTITION SMS  VALUES (1),
         SUBPARTITION other VALUES (DEFAULT))
      (PARTITION contact_20000 VALUES LESS THAN (20001),
       PARTITION contact_MAX VALUES LESS THAN (MAXVALUE))
        TABLESPACE DATA02
 ;


ALTER TABLE CONEADM.SMS_CLIENT_NOTIFICATION
       ADD  ( CONSTRAINT PK_SMS_CLIENT_NOTIFICATION PRIMARY KEY (
              CONTACT_EVENT_TYPE_ID, CONTACT_EVENT_ID, 
              KB_SUBSCRIBER_NO, KB_PRODUCT_TYPE, KB_BAN)
       USING INDEX
    	 TABLESPACE INDEX02 local ) ;

CREATE INDEX CONEADM.I_SMS_CLIENT_NOTIFICATION_01 ON 
CONEADM.SMS_CLIENT_NOTIFICATION
(
       SMS_GATEWAY_MESSAGE_ID         ASC
)
         TABLESPACE INDEX02
;

CREATE INDEX CONEADM.I_SMS_CLIENT_NOTIFICATION_02 ON 
CONEADM.SMS_CLIENT_NOTIFICATION
(
       SMS_STATUS_TYPE_CD             ASC,
       SCHEDULED_DELIVERY_DATETIME    ASC
)
         TABLESPACE INDEX02
;             



CREATE TABLE CONEADM.SMS_STATUS_TYPE (
       SMS_STATUS_TYPE_CD   VARCHAR2(20) NOT NULL,
       DESCRIPTION          VARCHAR2(100) NOT NULL,
       DESCRIPTION_FRENCH   VARCHAR2(100) NULL,
       CONTACT_EVENT_STATUS_CD VARCHAR2(1) NOT NULL,
       LOAD_DT              DATE NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
    	 TABLESPACE data01
 ;


ALTER TABLE CONEADM.SMS_STATUS_TYPE
       ADD  ( CONSTRAINT PK_SMS_STATUS_TYPE PRIMARY KEY (
              SMS_STATUS_TYPE_CD)
       USING INDEX
    	 TABLESPACE index01 ) ;

 

CREATE TABLE CONEADM.SOFTWARE_APPLICATION (
       SOFTWARE_APPLICATION_ID NUMBER(38) NOT NULL,
       NAME                 VARCHAR2(60) NOT NULL,
       DESCRIPTION          VARCHAR2(100) NULL,
       LOAD_DT              DATE NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
         TABLESPACE DATA01
 ;


ALTER TABLE CONEADM.SOFTWARE_APPLICATION
       ADD  ( CONSTRAINT PK_SOFTWARE_APPLICATION PRIMARY KEY (
              SOFTWARE_APPLICATION_ID)
       USING INDEX
         TABLESPACE INDEX01 ) ;

CREATE TABLE CONEADM.SUBSCRIBER_CONTACT_EVENT (
       CONTACT_EVENT_ID     NUMBER(38) NOT NULL,
       CONTACT_EVENT_TYPE_ID NUMBER(38) NOT NULL,
       KB_SUBSCRIBER_NO     VARCHAR(20) NOT NULL,
       KB_PRODUCT_TYPE      VARCHAR(1) NOT NULL,
       KB_BAN               NUMBER(9) NOT NULL,
       CONTACT_EVENT_STATUS_CODE VARCHAR2(1) NOT NULL,
       STATUS_TIMESTAMP     DATE NOT NULL,
       SUBSCRIPTION_ID      NUMBER NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL,
       STATUS_CONFIRMED_IND VARCHAR2(1) DEFAULT 'N' NULL,
       LANGUAGE_CD          VARCHAR2(2) NULL      
)
PARTITION BY RANGE (contact_event_id)
   SUBPARTITION BY LIST (contact_event_type_id)
      SUBPARTITION TEMPLATE
         (SUBPARTITION SMS  VALUES (1),
         SUBPARTITION other VALUES (DEFAULT))
      (PARTITION contact_20000 VALUES LESS THAN (20001),
       PARTITION contact_MAX VALUES LESS THAN (MAXVALUE))
        TABLESPACE DATA02
 ;


ALTER TABLE CONEADM.SUBSCRIBER_CONTACT_EVENT
       ADD  ( CONSTRAINT PK_SUBSCRIBER_CONTACT_EVENT PRIMARY KEY (
              CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID, 
              KB_SUBSCRIBER_NO, KB_PRODUCT_TYPE, KB_BAN)
       USING INDEX
    	 TABLESPACE INDEX02 local ) ;

CREATE TABLE CONEADM.LANGUAGE (
       LANGUAGE_CD          VARCHAR2(2) NOT NULL,
       LANGUAGE_DES         VARCHAR2(30) NULL,
       LANGUAGE_SHORT_CD    VARCHAR2(1) NOT NULL,
       LOAD_DT              DATE NOT NULL,
       UPDATE_DT            DATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) NOT NULL
)
         TABLESPACE DATA03
 ;


ALTER TABLE CONEADM.LANGUAGE
       ADD  ( CONSTRAINT PK_LANGUAGE PRIMARY KEY (LANGUAGE_CD)
       USING INDEX
         TABLESPACE INDEX03 ) ;   
                                

ALTER TABLE CONEADM.ALLOWED_CONT_EVENT_MECH
       ADD  ( CONSTRAINT FK_ALLOWED_CONT_EVENT_MECH_01
              FOREIGN KEY (CONTACT_EVENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_EVENT_TYPE ) ;


ALTER TABLE CONEADM.ALLOWED_CONT_EVENT_MECH
       ADD  ( CONSTRAINT FK_ALLOWED_CONT_EVENT_MECH_02
              FOREIGN KEY (CONTACT_MECHANISM_ID)
                             REFERENCES CONEADM.CONTACT_MECHANISM_TYPE ) ;


ALTER TABLE CONEADM.ALLOWED_CONTENT_MECHANISM
       ADD  ( CONSTRAINT FK_ALLOWED_CONTENT_MECHAN_01
              FOREIGN KEY (CONTACT_CONTENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_CONTENT_TYPE ) ;


ALTER TABLE CONEADM.ALLOWED_CONTENT_MECHANISM
       ADD  ( CONSTRAINT FK_ALLOWED_CONTENT_MECHAN_02
              FOREIGN KEY (CONTACT_EVENT_TYPE_ID, 
              CONTACT_MECHANISM_ID)
                             REFERENCES CONEADM.ALLOWED_CONT_EVENT_MECH ) ;


ALTER TABLE CONEADM.CLIENT_CONTACT_EVENT
       ADD  ( CONSTRAINT FK_CLIENT_CONTACT_EVENT_01
              FOREIGN KEY (CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_EVENT ) ;


ALTER TABLE CONEADM.CLIENT_CONTACT_EVENT
       ADD  ( CONSTRAINT FK_CLIENT_CONTACT_EVENT_02
              FOREIGN KEY (CONTACT_EVENT_STATUS_CODE)
                             REFERENCES CONEADM.CONTACT_EVENT_STATUS_TYPE ) ;


ALTER TABLE CONEADM.CONTACT_CONTENT_LANGUAGE
       ADD  ( CONSTRAINT FK_CONTACT_CONTENT_LANGUAGE_02
              FOREIGN KEY (LANGUAGE_CD)
                             REFERENCES CONEADM.LANGUAGE ) ;


ALTER TABLE CONEADM.CONTACT_CONTENT_LANGUAGE
       ADD  ( CONSTRAINT FK_CONTACT_CONTENT_LANGUAGE_01
              FOREIGN KEY (CONTACT_CONTENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_CONTENT_TYPE ) ;


ALTER TABLE CONEADM.CONTACT_CONTENT_PARAM_TYPE
       ADD  ( CONSTRAINT FK_CONTACT_CONTENT_PAR_TYPE_01
              FOREIGN KEY (CONTACT_CONTENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_CONTENT_TYPE ) ;


ALTER TABLE CONEADM.CONTACT_EVENT
       ADD  ( CONSTRAINT FK_CONTACT_EVENT_07
              FOREIGN KEY (ASSOCIATED_CONTACT_EVENT_ID, 
              CONTACT_EVENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_EVENT ) ;




ALTER TABLE CONEADM.CONTACT_EVENT
       ADD  ( CONSTRAINT FK_CONTACT_EVENT_04
              FOREIGN KEY (PROCESSING_SW_APPLICATION_ID)
                             REFERENCES CONEADM.SOFTWARE_APPLICATION ) ;


ALTER TABLE CONEADM.CONTACT_EVENT
       ADD  ( CONSTRAINT FK_CONTACT_EVENT_02
              FOREIGN KEY (CONTACT_EVENT_TYPE_ID, 
              CONTACT_MECHANISM_ID)
                             REFERENCES CONEADM.ALLOWED_CONT_EVENT_MECH ) ;


ALTER TABLE CONEADM.CONTACT_EVENT
       ADD  ( CONSTRAINT FK_CONTACT_EVENT_03
              FOREIGN KEY (CONTACT_CONTENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_CONTENT_TYPE ) ;


ALTER TABLE CONEADM.CONTACT_EVENT
       ADD  ( CONSTRAINT FK_CONTACT_EVENT_01
              FOREIGN KEY (CONTACT_EVENT_STATUS_CODE)
                             REFERENCES CONEADM.CONTACT_EVENT_STATUS_TYPE ) ;


ALTER TABLE CONEADM.CONTACT_EVENT_PURPOSE
       ADD  ( CONSTRAINT FK_CONTACT_EVENT_PURPOSE_02
              FOREIGN KEY (CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_EVENT ) ;


ALTER TABLE CONEADM.CONTACT_EVENT_PURPOSE
       ADD  ( CONSTRAINT FK_CONTACT_EVENT_PURPOSE_01
              FOREIGN KEY (CONTACT_EVENT_PURPOSE_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_EVENT_PURPOSE_TYPE ) ;


ALTER TABLE CONEADM.CONTACT_EVNT_CONTENT_PARAM
       ADD  ( CONSTRAINT FK_CONTACT_EVNT_CONTENT_PAR_01
              FOREIGN KEY (CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_EVENT ) ;


ALTER TABLE CONEADM.CONTACT_EVNT_CONTENT_PARAM
       ADD  ( CONSTRAINT FK_CONTACT_EVNT_CONTENT_PAR_02
              FOREIGN KEY (CONTACT_CONTENT_TYPE_ID, 
              CONTACT_CONTENT_PARAM_NO)
                             REFERENCES CONEADM.CONTACT_CONTENT_PARAM_TYPE ) ;


ALTER TABLE CONEADM.INDIVIDUAL_CONTACT_EVENT
       ADD  ( CONSTRAINT FK_INDIVIDUAL_CONTACT_EVENT_01
              FOREIGN KEY (CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_EVENT ) ;


ALTER TABLE CONEADM.INDIVIDUAL_CONTACT_EVENT
       ADD  ( CONSTRAINT FK_INDIVIDUAL_CONTACT_EVENT_02
              FOREIGN KEY (CONTACT_EVENT_STATUS_CODE)
                             REFERENCES CONEADM.CONTACT_EVENT_STATUS_TYPE ) ;


ALTER TABLE CONEADM.SMS_CLIENT_NOTIFICATION
       ADD  ( CONSTRAINT FK_SMS_CLIENT_NOTIFICATION_02
              FOREIGN KEY (SMS_STATUS_TYPE_CD)
                             REFERENCES CONEADM.SMS_STATUS_TYPE ) ;


ALTER TABLE CONEADM.SMS_CLIENT_NOTIFICATION
       ADD  ( CONSTRAINT FK_SMS_CLIENT_NOTIFICATION_01
              FOREIGN KEY (CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_EVENT ) ;


ALTER TABLE CONEADM.SMS_STATUS_TYPE
       ADD  ( CONSTRAINT FK_SMS_STATUS_TYPE_01
              FOREIGN KEY (CONTACT_EVENT_STATUS_CD)
                             REFERENCES CONEADM.CONTACT_EVENT_STATUS_TYPE ) ;


ALTER TABLE CONEADM.SUBSCRIBER_CONTACT_EVENT
       ADD  ( CONSTRAINT FK_SUBSCRIBER_CONTACT_EVENT_03
              FOREIGN KEY (LANGUAGE_CD)
                             REFERENCES CONEADM.LANGUAGE ) ;


ALTER TABLE CONEADM.SUBSCRIBER_CONTACT_EVENT
       ADD  ( CONSTRAINT FK_SUBSCRIBER_CONTACT_EVENT_01
              FOREIGN KEY (CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID)
                             REFERENCES CONEADM.CONTACT_EVENT ) ;


ALTER TABLE CONEADM.SUBSCRIBER_CONTACT_EVENT
       ADD  ( CONSTRAINT FK_SUBSCRIBER_CONTACT_EVENT_02
              FOREIGN KEY (CONTACT_EVENT_STATUS_CODE)
                             REFERENCES CONEADM.CONTACT_EVENT_STATUS_TYPE ) ;



