
package com.telus.cmb.endpoint;

import javax.jws.WebService;
import javax.xml.ws.BindingType;
import com.telus.cmb.schema.ActivatePortInRequest;
import com.telus.cmb.schema.ActivatePortInRequestResponse;
import com.telus.cmb.schema.ActivateSubscriber;
import com.telus.cmb.schema.ActivateSubscriberResponse;
import com.telus.cmb.schema.ChangeEquipment;
import com.telus.cmb.schema.ChangeEquipmentResponse;
import com.telus.cmb.schema.ChangePhoneNumber;
import com.telus.cmb.schema.ChangePhoneNumberResponse;
import com.telus.cmb.schema.ChangeVoipNumber;
import com.telus.cmb.schema.ChangeVoipNumberResponse;
import com.telus.cmb.schema.ChangeVoipNumberWithCharge;
import com.telus.cmb.schema.ChangeVoipNumberWithChargeResponse;
import com.telus.cmb.schema.GetServiceAgreement;
import com.telus.cmb.schema.GetServiceAgreementForUpdate;
import com.telus.cmb.schema.GetServiceAgreementForUpdateResponse;
import com.telus.cmb.schema.GetServiceAgreementResponse;
import com.telus.cmb.schema.MigrateSeat;
import com.telus.cmb.schema.MigrateSeatResponse;
import com.telus.cmb.schema.MigrateSubscriber;
import com.telus.cmb.schema.MigrateSubscriberResponse;
import com.telus.cmb.schema.MoveVoipNumberBetweenSeats;
import com.telus.cmb.schema.MoveVoipNumberBetweenSeatsResponse;
import com.telus.cmb.schema.PrepopulateCallingCircleList;
import com.telus.cmb.schema.PrepopulateCallingCircleListResponse;
import com.telus.cmb.schema.ResetCscSubscription;
import com.telus.cmb.schema.ResetCscSubscriptionResponse;
import com.telus.cmb.schema.SaveServiceAgreement;
import com.telus.cmb.schema.SaveServiceAgreementResponse;
import com.telus.cmb.schema.ValidateMigrateSeat;
import com.telus.cmb.schema.ValidateMigrateSeatResponse;
import com.telus.cmb.schema.ValidateMigrateSubscriber;
import com.telus.cmb.schema.ValidateMigrateSubscriberResponse;
import com.telus.cmb.schema.ValidateServiceAgreement;
import com.telus.cmb.schema.ValidateServiceAgreementResponse;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v2.Ping;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v2.PingResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebService(portName = "SubscriberManagementServicePort", serviceName = "SubscriberManagementService_v4_2_1", targetNamespace = "http://telus.com/wsdl/CMO/OrderMgmt/SubscriberManagementService_4", wsdlLocation = "classpath:wsdls/SubscriberManagementService_v4_2_1.wsdl", endpointInterface = "com.telus.cmb.endpoint.SubscriberManagementServicePort")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class SubscriberManagementService_v4_2_1_SubscriberManagementServicePortImpl
    implements SubscriberManagementServicePort
{


    public SubscriberManagementService_v4_2_1_SubscriberManagementServicePortImpl() {
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.ChangeEquipmentResponse
     * @throws EndpointException
     */
    public ChangeEquipmentResponse changeEquipment(ChangeEquipment parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.ChangePhoneNumberResponse
     * @throws EndpointException
     */
    public ChangePhoneNumberResponse changePhoneNumber(ChangePhoneNumber parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.ChangeVoipNumberResponse
     * @throws EndpointException
     */
    public ChangeVoipNumberResponse changeVoipNumber(ChangeVoipNumber parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.ChangeVoipNumberWithChargeResponse
     * @throws EndpointException
     */
    public ChangeVoipNumberWithChargeResponse changeVoipNumberWithCharge(ChangeVoipNumberWithCharge parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.MoveVoipNumberBetweenSeatsResponse
     * @throws EndpointException
     */
    public MoveVoipNumberBetweenSeatsResponse moveVoipNumberBetweenSeats(MoveVoipNumberBetweenSeats parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.GetServiceAgreementResponse
     * @throws EndpointException
     */
    public GetServiceAgreementResponse getServiceAgreement(GetServiceAgreement parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.GetServiceAgreementForUpdateResponse
     * @throws EndpointException
     */
    public GetServiceAgreementForUpdateResponse getServiceAgreementForUpdate(GetServiceAgreementForUpdate parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.ValidateServiceAgreementResponse
     * @throws EndpointException
     */
    public ValidateServiceAgreementResponse validateServiceAgreement(ValidateServiceAgreement parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.SaveServiceAgreementResponse
     * @throws EndpointException
     */
    public SaveServiceAgreementResponse saveServiceAgreement(SaveServiceAgreement parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.PrepopulateCallingCircleListResponse
     * @throws EndpointException
     */
    public PrepopulateCallingCircleListResponse prepopulateCallingCircleList(PrepopulateCallingCircleList parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.ValidateMigrateSubscriberResponse
     * @throws EndpointException
     */
    public ValidateMigrateSubscriberResponse validateMigrateSubscriber(ValidateMigrateSubscriber parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.MigrateSubscriberResponse
     * @throws EndpointException
     */
    public MigrateSubscriberResponse migrateSubscriber(MigrateSubscriber parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.ValidateMigrateSeatResponse
     * @throws EndpointException
     */
    public ValidateMigrateSeatResponse validateMigrateSeat(ValidateMigrateSeat parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.MigrateSeatResponse
     * @throws EndpointException
     */
    public MigrateSeatResponse migrateSeat(MigrateSeat parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.ResetCscSubscriptionResponse
     * @throws EndpointException
     */
    public ResetCscSubscriptionResponse resetCscSubscription(ResetCscSubscription parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.ActivateSubscriberResponse
     * @throws EndpointException
     */
    public ActivateSubscriberResponse activateSubscriber(ActivateSubscriber parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.cmb.schema.ActivatePortInRequestResponse
     * @throws EndpointException
     */
    public ActivatePortInRequestResponse activatePortInRequest(ActivatePortInRequest parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns com.telus.tmi.xmlschema.xsd.enterprise.basetypes.types.ping_v2.PingResponse
     * @throws EndpointException
     */
    public PingResponse ping(Ping parameters)
        throws EndpointException
    {
        //replace with your impl here
        return null;
    }

}
