Drop table CONEADM.CONTACT_EVENT_TEAM_MEMBER ;
CREATE TABLE CONTACT_EVENT_TEAM_MEMBER (
       CONTACT_EVENT_ID     NUMBER(38) NOT NULL,
       CONTACT_EVENT_TYPE_ID NUMBER(38) NOT NULL,
       TEAM_MEMBER_ID       NUMBER(22) NOT NULL,
       LOAD_DT              DATE DEFAULT SYSDATE NOT NULL,
       UPDATE_DT            DATE DEFAULT SYSDATE NOT NULL,
       USER_LAST_MODIFY     VARCHAR2(30) DEFAULT USER NOT NULL
)
PARTITION BY RANGE (contact_event_id)
   SUBPARTITION BY LIST (contact_event_type_id)
      SUBPARTITION TEMPLATE
         (SUBPARTITION SMS  VALUES (1),
         SUBPARTITION other VALUES (DEFAULT))
      (PARTITION contact_20000 VALUES LESS THAN (20001),
       PARTITION contact_MAX VALUES LESS THAN (MAXVALUE))
        TABLESPACE DATA02;



ALTER TABLE CONTACT_EVENT_TEAM_MEMBER
       ADD ( CONSTRAINT PK_CONTACT_EVENT_TEAM_MEMBER PRIMARY KEY (
              CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID, TEAM_MEMBER_ID)
       USING INDEX
    	 TABLESPACE INDEX02 local);

CREATE PUBLIC SYNONYM CONTACT_EVENT_TEAM_MEMBER FOR CONTACT_EVENT_TEAM_MEMBER;

GRANT DELETE ON CONTACT_EVENT_TEAM_MEMBER TO CONE_FULL;
GRANT INSERT ON CONTACT_EVENT_TEAM_MEMBER TO CONE_FULL;
GRANT SELECT ON CONTACT_EVENT_TEAM_MEMBER TO CONE_read,CONE_FULL;
GRANT UPDATE ON CONTACT_EVENT_TEAM_MEMBER TO CONE_FULL;

GRANT DELETE ON CONTACT_EVENT_TEAM_MEMBER TO vetrovka_s;
GRANT INSERT ON CONTACT_EVENT_TEAM_MEMBER TO vetrovka_s;
GRANT SELECT ON CONTACT_EVENT_TEAM_MEMBER TO vetrovka_s;
GRANT UPDATE ON CONTACT_EVENT_TEAM_MEMBER TO vetrovka_s;


ALTER TABLE CONTACT_EVENT_TEAM_MEMBER
       ADD CONSTRAINT FK_CONTACT_EVENT_TEAM_MEMBR_01
              FOREIGN KEY (CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID)
                             REFERENCES CONTACT_EVENT  (
              CONTACT_EVENT_ID, CONTACT_EVENT_TYPE_ID);



