INSERT INTO CONTACT_EVENT_TYPE (CONTACT_EVENT_TYPE_ID, DESCRIPTION, DESCRIPTION_FRENCH, OUTBOUND_INDICATOR, USER_LAST_MODIFY) VALUES (116, 'Inter-brand Port Success', 'Inter-Port de marque de réussite', 'Y', 'CONEADM');

INSERT INTO ALLOWED_CONT_EVENT_MECH (CONTACT_EVENT_TYPE_ID, CONTACT_MECHANISM_ID, USER_LAST_MODIFY) VALUES (116, 1, 'CONEADM');

INSERT INTO CONTACT_CONTENT_TYPE (CONTACT_CONTENT_TYPE_ID, DESCRIPTION, DESCRIPTION_FRENCH, BILLABLE_INDICATOR, DELIVERY_RECEIPT_REQ_IND, USER_LAST_MODIFY) VALUES
(213, 'Inter-brand Port Success', 'Inter-Port de marque de réussite', 'N', 'N', 'CONEADM');

INSERT INTO ALLOWED_CONTENT_MECHANISM(CONTACT_CONTENT_TYPE_ID, CONTACT_EVENT_TYPE_ID, CONTACT_MECHANISM_ID, USER_LAST_MODIFY) VALUES (213, 116, 1, 'CONEADM');

INSERT INTO CONTACT_CONTENT_LANGUAGE (CONTACT_CONTENT_TYPE_ID, LANGUAGE_CD, TEMPLATE_TEXT, USER_LAST_MODIFY) VALUES
(213, 'EN', 'From ?: Your transfer request has been completed successfully. Welcome to ? and thank you for joining us!' , 'CONEADM');

INSERT INTO CONTACT_CONTENT_LANGUAGE (CONTACT_CONTENT_TYPE_ID, LANGUAGE_CD, TEMPLATE_TEXT, USER_LAST_MODIFY) VALUES
(213, 'FR', 'De ?: Votre demande de transfert a été complétée avec succès. Bienvenue chez ? et merci de vous joindre à nous!' , 'CONEADM');

INSERT INTO CONTACT_CONTENT_PARAM_TYPE (CONTACT_CONTENT_TYPE_ID, CONTACT_CONTENT_PARAM_NO, DESCRIPTION, DESCRIPTION_FRENCH, USER_LAST_MODIFY) VALUES
(213, 1, 'Brand Name', 'Nom de marque', 'CONEADM');

INSERT INTO CONTACT_CONTENT_PARAM_TYPE (CONTACT_CONTENT_TYPE_ID, CONTACT_CONTENT_PARAM_NO, DESCRIPTION, DESCRIPTION_FRENCH, USER_LAST_MODIFY) VALUES
(213, 2, 'Brand Name', 'Nom de marque', 'CONEADM');
