DELETE FROM CONTACT_CONTENT_PARAM_TYPE WHERE CONTACT_CONTENT_TYPE_ID = 213
DELETE FROM CONTACT_CONTENT_LANGUAGE WHERE CONTACT_CONTENT_TYPE_ID = 213
DELETE FROM ALLOWED_CONTENT_MECHANISM WHERE CONTACT_CONTENT_TYPE_ID = 213 AND CONTACT_EVENT_TYPE_ID = 116 AND CONTACT_MECHANISM_ID = 1
DELETE FROM CONTACT_CONTENT_TYPE WHERE CONTACT_CONTENT_TYPE_ID = 213
DELETE FROM ALLOWED_CONT_EVENT_MECH WHERE CONTACT_EVENT_TYPE_ID = 116 AND CONTACT_MECHANISM_ID = 1
DELETE FROM CONTACT_EVENT_TYPE WHERE CONTACT_EVENT_TYPE_ID = 116