SELECT BAN,
  SUBSCRIBER_NO,
  RECORD_TYPE,
  AIRTIME_FEATURE_CD,
  PRICE_PLAN_CODE,
  ACTION_DIRECTION_CD,
  SOC_EFFECTIVE_DATE,
  IM_ALLOCATION_IND,
  TOTAL_CALLS,
  NUM_OF_CALLS_1,
  NUM_OF_CALLS_2,
  NUM_OF_CALLS_3,
  NUM_OF_CALLS_4,
  NUM_OF_CALLS_5,
  NUM_OF_CALLS_6,
  NUM_FREE_AIR_CALLS,
  NUM_SPECIAL_CALLS,
  TOTAL_USED,
  TOTAL_USED_1,
  TOTAL_USED_2,
  TOTAL_USED_3,
  TOTAL_USED_4,
  TOTAL_USED_5,
  TOTAL_USED_6,
  IM_ALLOWED,
  IM_ALLOWED_COMBD IM_ALLOWED,
  IM_ALLOWED_1,
  IM_ALLOWED_2,
  IM_ALLOWED_3,
  IM_ALLOWED_4,
  IM_ALLOWED_5,
  IM_ALLOWED_6,
  IM_USED,
  IM_USED_1,
  IM_USED_2,
  IM_USED_3,
  IM_USED_4,
  IM_USED_5,
  IM_USED_6,
  FREE,
  FREE_1,
  FREE_2,
  FREE_3,
  FREE_4,
  FREE_5,
  FREE_6,
  UNIT_OF_MEASURE,
  PRODUCT_TYPE,
  DECODE( record_type,7,0,(GREATEST(IM_ALLOWED_COMBD                                       - IM_USED,0)) ) im_remaining,
  DECODE( IM_ALLOWED_COMBD, 0, GREATEST(IM_ALLOWED_1                                         - IM_USED_1 ,0), 0 ) im_remaining_1,
  DECODE( IM_ALLOWED_COMBD, 0, GREATEST(IM_ALLOWED_2                                         - IM_USED_2 ,0), 0 ) im_remaining_2,
  DECODE( IM_ALLOWED_COMBD, 0, GREATEST(IM_ALLOWED_3                                         - IM_USED_3 ,0), 0 ) im_remaining_3,
  DECODE( IM_ALLOWED_COMBD, 0, GREATEST(IM_ALLOWED_4                                         - IM_USED_4 ,0), 0 ) im_remaining_4,
  DECODE( IM_ALLOWED_COMBD, 0, GREATEST(IM_ALLOWED_5                                         - IM_USED_5 ,0), 0 ) im_remaining_5,
  DECODE( IM_ALLOWED_COMBD, 0, GREATEST(IM_ALLOWED_6                                         - IM_USED_6 ,0), 0 ) im_remaining_6,
  DECODE( upper(UNIT_OF_MEASURE),'M', DECODE( IM_ALLOWED_COMBD, IM_USED_COMBD, (TOTAL_USED   - IM_USED - FREE), 0 ), (TOTAL_CALLS - IM_USED ) ) chargeable,
  DECODE( upper(UNIT_OF_MEASURE),'M', DECODE( IM_ALLOWED_COMBD, IM_USED_COMBD, (TOTAL_USED_1 - IM_USED_1 - FREE_1), 0 ), (NUM_OF_CALLS_1 - IM_USED_1 ) ) chargeable_1,
  DECODE( upper(UNIT_OF_MEASURE),'M', DECODE( IM_ALLOWED_COMBD, IM_USED_COMBD, (TOTAL_USED_2 - IM_USED_2 - FREE_2), 0 ), (NUM_OF_CALLS_2 - IM_USED_2 ) ) chargeable_2,
  DECODE( upper(UNIT_OF_MEASURE),'M', DECODE( IM_ALLOWED_COMBD, IM_USED_COMBD, (TOTAL_USED_3 - IM_USED_3 - FREE_3), 0 ), (NUM_OF_CALLS_3 - IM_USED_3 ) ) chargeable_3,
  DECODE( upper(UNIT_OF_MEASURE),'M', DECODE( IM_ALLOWED_COMBD, IM_USED_COMBD, (TOTAL_USED_4 - IM_USED_4 - FREE_4), 0 ), (NUM_OF_CALLS_4 - IM_USED_4 ) ) chargeable_4,
  DECODE( upper(UNIT_OF_MEASURE),'M', DECODE( IM_ALLOWED_COMBD, IM_USED_COMBD, (TOTAL_USED_5 - IM_USED_5 - FREE_5), 0 ), (NUM_OF_CALLS_5 - IM_USED_5 ) ) chargeable_5,
  DECODE( upper(UNIT_OF_MEASURE),'M', DECODE( IM_ALLOWED_COMBD, IM_USED_COMBD, (TOTAL_USED_6 - IM_USED_6 - FREE_6), 0 ), (NUM_OF_CALLS_6 - IM_USED_6 ) ) chargeable_6,
  TOTAL_CHARGE,
  CHARGE_1,
  CHARGE_2,
  CHARGE_3,
  CHARGE_4,
  CHARGE_5,
  CHARGE_6,
  DECODE( record_type,7,GREATEST(0,IM_ALLOWED   - TOTAL_CHARGE) ,0) AP_REMAINING,
  DECODE( record_type,7,GREATEST(0,TOTAL_CHARGE - IM_ALLOWED) ,0) AP_CHARGE,
  TO_CHAR(LAST_CALL_DATE,'YYYY-MM-DD') LAST_CALL_DATE,
  PRORATION_IND,
  RATING_LEVEL_CODE
FROM
  (SELECT MAX ( au.BAN ) ban,
    MAX ( SUBSCRIBER_NO ) subscriber_no,
    RECORD_TYPE,
    AIRTIME_FEATURE_CD,
    PRICE_PLAN_CODE,
    ACTION_DIRECTION_CD,
    MAX(SOC_EFFECTIVE_DATE) SOC_EFFECTIVE_DATE,
    MAX(RATING_LEVEL_CODE) RATING_LEVEL_CODE,
    MAX( PRODUCT_TYPE ) PRODUCT_TYPE,
    MAX( IM_ALLOCATION_IND ) IM_ALLOCATION_IND,
    SUM( NUM_OF_CALLS_PRD_1 + NUM_OF_CALLS_PRD_2 + NUM_OF_CALLS_PRD_3 + NUM_OF_CALLS_PRD_4 + NUM_OF_CALLS_PRD_5 + NUM_OF_CALLS_PRD_6 + NUM_OF_CALLS ) total_calls,
    SUM( NUM_OF_CALLS_PRD_1 ) num_of_calls_1,
    SUM( NUM_OF_CALLS_PRD_2 ) num_of_calls_2,
    SUM( NUM_OF_CALLS_PRD_3 ) num_of_calls_3,
    SUM( NUM_OF_CALLS_PRD_4 ) num_of_calls_4,
    SUM( NUM_OF_CALLS_PRD_5 ) num_of_calls_5,
    SUM( NUM_OF_CALLS_PRD_6 ) num_of_calls_6,
    SUM( NUM_OF_FREE_AIR_CALLS ) num_free_air_calls,
    SUM( NUM_OF_NO_AIR_CALLS ) num_special_calls,
    SUM( CTN_MINS_PRD_1 + CTN_MINS_PRD_2 + CTN_MINS_PRD_3 + CTN_MINS_PRD_4 + CTN_MINS_PRD_5 + CTN_MINS_PRD_6 + CTN_MINS ) total_used,
    SUM( CTN_MINS_PRD_1 ) total_used_1,
    SUM( CTN_MINS_PRD_2 ) total_used_2,
    SUM( CTN_MINS_PRD_3 ) total_used_3,
    SUM( CTN_MINS_PRD_4 ) total_used_4,
    SUM( CTN_MINS_PRD_5 ) total_used_5,
    SUM( CTN_MINS_PRD_6 ) total_used_6,
    SUM ( CHRG_AMT_PRD_1 + CHRG_AMT_PRD_2 + CHRG_AMT_PRD_3 + CHRG_AMT_PRD_4 + CHRG_AMT_PRD_5 + CHRG_AMT_PRD_6 + CHRG_AMT ) total_charge,
    SUM (CHRG_AMT_PRD_1) charge_1,
    SUM (CHRG_AMT_PRD_2) charge_2,
    SUM (CHRG_AMT_PRD_3) charge_3,
    SUM (CHRG_AMT_PRD_4) charge_4,
    SUM (CHRG_AMT_PRD_5) charge_5,
    SUM (CHRG_AMT_PRD_6) charge_6,
    SUM (ROUND( NVL(IM_ALLOWED_COMBD,0)                                  * DECODE (NVL(PRORATION_FACTOR,0),0,1,PRORATION_FACTOR) ) ) im_allowed_combd,
    SUM (DECODE( NVL(IM_ALLOWED_COMBD,0), 0 , ( (NVL(IM_ALLOWED_PRD_1,0) + NVL(IM_ALLOWED_PRD_2,0) + NVL(IM_ALLOWED_PRD_3,0) + NVL(IM_ALLOWED_PRD_4,0) + NVL(IM_ALLOWED_PRD_5,0) + NVL(IM_ALLOWED_PRD_6,0) ) * DECODE (NVL(PRORATION_FACTOR,0),0,1,PRORATION_FACTOR) ), ( NVL(IM_ALLOWED_COMBD,0) * DECODE (NVL(PRORATION_FACTOR,0),0,1,PRORATION_FACTOR) ) ) ) im_allowed,
    SUM (NVL(IM_ALLOWED_PRD_1,0)                                         * DECODE (NVL(PRORATION_FACTOR,0),0,1,PRORATION_FACTOR) ) im_allowed_1,
    SUM (NVL(IM_ALLOWED_PRD_2,0)                                         * DECODE (NVL(PRORATION_FACTOR,0),0,1,PRORATION_FACTOR) ) im_allowed_2,
    SUM (NVL(IM_ALLOWED_PRD_3,0)                                         * DECODE (NVL(PRORATION_FACTOR,0),0,1,PRORATION_FACTOR) ) im_allowed_3,
    SUM (NVL(IM_ALLOWED_PRD_4,0)                                         * DECODE (NVL(PRORATION_FACTOR,0),0,1,PRORATION_FACTOR) ) im_allowed_4,
    SUM (NVL(IM_ALLOWED_PRD_5,0)                                         * DECODE (NVL(PRORATION_FACTOR,0),0,1,PRORATION_FACTOR) ) im_allowed_5,
    SUM (NVL(IM_ALLOWED_PRD_6,0)                                         * DECODE (NVL(PRORATION_FACTOR,0),0,1,PRORATION_FACTOR) ) im_allowed_6,
    SUM ( CTN_IM_USED_COMBD ) im_used_combd,
    SUM ( DECODE( CTN_IM_USED_COMBD, 0 , ( CTN_IM_USED_PRD_1 + CTN_IM_USED_PRD_2 + CTN_IM_USED_PRD_3 + CTN_IM_USED_PRD_4 + CTN_IM_USED_PRD_5 + CTN_IM_USED_PRD_6 ), CTN_IM_USED_COMBD ) ) im_used,
    SUM( CTN_IM_USED_PRD_1 ) im_used_1,
    SUM( CTN_IM_USED_PRD_2 ) im_used_2,
    SUM( CTN_IM_USED_PRD_3 ) im_used_3,
    SUM( CTN_IM_USED_PRD_4 ) im_used_4,
    SUM( CTN_IM_USED_PRD_5 ) im_used_5,
    SUM( CTN_IM_USED_PRD_6 ) im_used_6,
    SUM ( FREE_MIN_USED_PRD_1 + FREE_MIN_USED_PRD_2 + FREE_MIN_USED_PRD_3 + FREE_MIN_USED_PRD_4 + FREE_MIN_USED_PRD_5 + FREE_MIN_USED_PRD_6 ) free,
    SUM (FREE_MIN_USED_PRD_1) free_1,
    SUM (FREE_MIN_USED_PRD_2) free_2,
    SUM (FREE_MIN_USED_PRD_3) free_3,
    SUM (FREE_MIN_USED_PRD_4) free_4,
    SUM (FREE_MIN_USED_PRD_5) free_5,
    SUM (FREE_MIN_USED_PRD_6) free_6,
    MIN( DECODE( trim(UNIT_MEASUR_CODE), NULL, DECODE(airtime_feature_cd,'MMMAIL','s','m'), trim(UNIT_MEASUR_CODE) ) ) unit_of_measure,
    MAX( LAST_IM_CALL_DT ) last_call_date,
    MAX( DECODE(NVL(PRORATION_FACTOR,0),1,'N',0,'N','Y') ) proration_ind
  FROM :usage_table au
  JOIN billing_account ba
  ON au.ban                                   = ba.ban
  WHERE record_type                           = :record_type
  AND airtime_feature_cd                      = :feature_code
  AND au.ban                                  = :ban
  AND bl_cur_bill_seq_no                      = bill_seq_no
  AND ( NVL(trim(im_allocation_ind),'?') NOT IN ('N') )
  GROUP BY subscriber_no,
    record_type,
    airtime_feature_cd,
    price_plan_code,
    action_direction_cd
  )
ORDER BY ban,
  subscriber_no,
  record_type,
  airtime_feature_cd,
  soc_effective_date,
  price_plan_code,
  action_direction_cd