ALTER TABLE CC_FRAUD_ADM.APP_TMPG_MESSAGES
  MODIFY (TMPG_CODE  VARCHAR2(30) );
  
DELETE APP_TMPG_MESSAGES WHERE APP_ROLE_ID = 'ECA_WPS';  

/*
INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT80001', '100');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT80002', '100');
						
INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT80003', '100');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT80004', '100');

*/

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17001', '300');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17002', '300');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17082', '300');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17080', '300');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17003', '101');

/*		
INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17026', '100');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17027', '100');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17028', '100');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17029', '100');
		
INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17030', '100');
		
INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17031', '100');
*/
		
INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17040', '103');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17041', '103');
		
INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17042', '103');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17043', '103');

INSERT INTO APP_TMPG_MESSAGES ( APP_ROLE_ID, TMPG_CODE, RESPONSE_CODE) 
		VALUES ( 'ECA_WPS', 'PYMT17070', '102');
		
COMMIT;

						