--step 1: insert velocity config for EKW_3

DELETE FROM VELOCITY_CONFIG WHERE APPID = 'EKW_3';

INSERT INTO VELOCITY_CONFIG
(APPID,TRANSACTIONS_PER_DAY,TRANSACTIONS_PER_MONTH,DAY_TOTAL,MONTH_TOTAL)
VALUES ('EKW_3',2,2,1500,1500);

commit;