--step 1: insert velocity config for EKW

DELETE FROM VELOCITY_CONFIG WHERE APPID = 'EKW';

INSERT INTO VELOCITY_CONFIG
(APPID,TRANSACTIONS_PER_DAY,TRANSACTIONS_PER_MONTH,DAY_TOTAL,MONTH_TOTAL)
VALUES ('EKW_3',1,1,750,750);

commit;