DELETE FROM APP_MESSAGES WHERE APP_ROLE_ID IN ('AMDOCS_DEFAULT', 'AMDOCS_CLIENT', 'AMDOCS_AGENT')
AND RESPONSE_CODE = '104';

DELETE FROM APP_TMPG_MESSAGES WHERE APP_ROLE_ID = 'ECA_WPS' AND TMPG_CODE = 'AV100051' AND RESPONSE_CODE = '104'

COMMIT;