
package com.telus.cmb.wsclient;

import javax.xml.ws.WebFault;
import com.telus.tmi.xmlschema.xsd.common.exceptions.exceptions_v1_0.PolicyFaultInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "PolicyException", targetNamespace = "http://xmlschema.tmi.telus.com/xsd/common/exceptions/Exceptions_v1_0")
public class PolicyException_v1
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PolicyFaultInfo faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PolicyException_v1(String message, PolicyFaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PolicyException_v1(String message, PolicyFaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.telus.tmi.xmlschema.xsd.common.exceptions.exceptions_v1_0.PolicyFaultInfo
     */
    public PolicyFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
