
package com.telus.cmb.wsclient;

import javax.xml.ws.WebFault;
import com.telus.tmi.xmlschema.xsd.enterprise.basetypes.exceptions_v3.FaultExceptionDetailsType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ServiceException", targetNamespace = "http://xmlschema.tmi.telus.com/xsd/Enterprise/BaseTypes/Exceptions_v3")
public class ServiceException_v3
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultExceptionDetailsType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServiceException_v3(String message, FaultExceptionDetailsType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServiceException_v3(String message, FaultExceptionDetailsType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.telus.tmi.xmlschema.xsd.enterprise.basetypes.exceptions_v3.FaultExceptionDetailsType
     */
    public FaultExceptionDetailsType getFaultInfo() {
        return faultInfo;
    }

}
