/* Generated by Together */

package com.telus.api.equipment;

import com.telus.api.reference.*;
import com.telus.api.*;

@Deprecated
public interface PagerEquipment extends Equipment {
  // Pager encoding formats
  static final String ENCODING_FORMAT_FLEX = "F";
  static final String ENCODING_FORMAT_GOLAY = "G";
  static final String ENCODING_FORMAT_NETWORK = "N";
  static final String ENCODING_FORMAT_POCSAG = "P";
  static final String ENCODING_FORMAT_SPOCSAG = "S";
  static final String ENCODING_FORMAT_5TONE = "Y";

  // Pager equipment types
  static final String EQUIPMENT_TYPE_VOICE = "V";
  static final String EQUIPMENT_TYPE_TONE = "T";
  static final String EQUIPMENT_TYPE_NUMERIC = "N";
  static final String EQUIPMENT_TYPE_ALPHA = "L";
  static final String EQUIPMENT_TYPE_ENCODER = "E";
  static final String EQUIPMENT_TYPE_GREETING = "G";
  static final String EQUIPMENT_TYPE_ALPHAMAIL = "M";
  static final String EQUIPMENT_TYPE_TONEANDVOICE = "O";

  String getCapCode();

  String getFormattedCapCode();

  CoverageRegion[] getCoverageRegion() throws TelusAPIException ;

  String getCurrentCoverageRegionCode();

  void setCurrentCoverageRegionCode(String currentCoverageRegionCode);

  String getEncodingFormat();

  String getPossession();

  void setPossession(String possession);

  String getFrequencyCode();

  void setEquipmentType(String newEquipmentType);

  String getModelType();

  boolean isBoxed();

  boolean isRental();
}
