DELETE FROM MESSAGE_RULE_CONDITION_ASSN ;
DELETE FROM MESSAGE_RULE ;
DELETE FROM RULE_CONDITION_VALUE ;
DELETE FROM RULE_CONDITION ;
DELETE FROM RULE_CONDITION_TYPE ;
DELETE FROM MESSAGE_RULE_TYPE ;
DELETE FROM MESSAGE_ROLE_TYPE ;
DELETE FROM MESSAGE_RULE_CLASSIFICATION ;
DELETE FROM RULE_RESULT_TYPE ;

COMMIT;

