
DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=99 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=99 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=92 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=92 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=157 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=157 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=207 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=207 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=93 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=93 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=94 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=94 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=96 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=96 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=97 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=97 AND ADAPTED_MESSAGE_SEQ=8;
 
DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=98 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=98 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=100 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=100 AND ADAPTED_MESSAGE_SEQ=8;
 
DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=156 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=156 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=102 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=102 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=103 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=103 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=104 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=104 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=105 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=105 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=106 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=106 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=107 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=107 AND ADAPTED_MESSAGE_SEQ=8;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=109 AND ADAPTED_MESSAGE_SEQ=7;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=109 AND ADAPTED_MESSAGE_SEQ=8;
   
DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=99 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=92 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=157 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=207 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=93 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=94 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=96 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=97 AND ADAPTED_MESSAGE_SEQ=9;
 
DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=98 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=100 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=156 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=102 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=103 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=104 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=105 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=106 AND ADAPTED_MESSAGE_SEQ=9;

DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=107 AND ADAPTED_MESSAGE_SEQ=9;
 
DELETE ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID=109 AND ADAPTED_MESSAGE_SEQ=9;

commit;

 