
DELETE FROM ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID = 326 AND ADAPTED_MESSAGE_SEQ=1

DELETE FROM ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID = 326 AND ADAPTED_MESSAGE_SEQ=2

DELETE FROM ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID = 327 AND ADAPTED_MESSAGE_SEQ=1

DELETE FROM ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID = 327 AND ADAPTED_MESSAGE_SEQ=2

-- SCORPION additions
DELETE FROM ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID = 328 AND ADAPTED_MESSAGE_SEQ = 1

DELETE FROM ADAPTED_MESSAGE WHERE APPLICATION_MESSAGE_ID = 328 AND ADAPTED_MESSAGE_SEQ = 2
