INSERT INTO GENERIC_CODES_EXT (GENERIC_TYPE, GENERIC_CODE, DESCRIPTION, DESCRIPTION_F)
  VALUES ( 'CATEGORY_CODE','CF','Call Free','Call Free');
commit;

INSERT INTO FEATURE_CATEGORY_RELATION (FEATURE_CODE, CATEGORY_CODE)
	VALUES ('CHF', 'CF');
	
INSERT INTO FEATURE_CATEGORY_RELATION (FEATURE_CODE, CATEGORY_CODE)
	VALUES ('CHFB', 'CF');

COMMIT;