INSERT INTO GENERIC_CODES_EXT (GENERIC_TYPE, GENERIC_CODE, DESCRIPTION, DESCRIPTION_F)
  VALUES ( 'MIGRATION_TYPE','MKPO','Migrate from MiKE to PCS Post-paid','Migrate from MiKE to PCS Post-paid');
INSERT INTO GENERIC_CODES_EXT (GENERIC_TYPE, GENERIC_CODE, DESCRIPTION, DESCRIPTION_F)
  VALUES ( 'MIGRATION_TYPE','MKPR','Migrate from MiKE to PCS Pre-paid','Migrate from MiKE to PCS Pre-paid');
INSERT INTO GENERIC_CODES_EXT (GENERIC_TYPE, GENERIC_CODE, DESCRIPTION, DESCRIPTION_F)
  VALUES ( 'MIGRATION_TYPE','POMK','Migrate from PCS Post-paid to MiKE','Migrate from PCS Post-paid to MiKE');
INSERT INTO GENERIC_CODES_EXT (GENERIC_TYPE, GENERIC_CODE, DESCRIPTION, DESCRIPTION_F)
  VALUES ( 'MIGRATION_TYPE','PRMK','Migrate from PCS Pre-paid to MiKE','Migrate from PCS Pre-paid to MiKE');
commit;
