/* Generated by Together */

package com.telus.eas.subscriber.info;


public class HSPASubscriberInfo extends PCSSubscriberInfo  {

  static final long serialVersionUID = 1L;

  private String  hspaImsi;
  
	public String getHspaImsi() {
		return hspaImsi;
	}

	public void setHspaImsi(String hspaImsi) {
		this.hspaImsi = hspaImsi;
	}
	
	public boolean isHSPA() {
		return true;
	}
	
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("HSPASubscriberInfo[");
		buffer.append("hspaImsi = ").append(hspaImsi);
		buffer.append(super.toString()).append("]\n");
		buffer.append("]");
		return buffer.toString();
	}

	
}
