/* Generated by Together */

package com.telus.eas.subscriber.info;

import java.util.Date;

import com.telus.api.TelusAPIException;
import com.telus.api.account.InvalidEquipmentChangeException;
import com.telus.api.account.PagerSubscriber;
import com.telus.api.account.SerialNumberInUseException;
import com.telus.api.equipment.Equipment;
import com.telus.api.equipment.InvalidPagerEquipmentException;
import com.telus.api.equipment.PagerEquipment;

@Deprecated
public class PagerSubscriberInfo extends SubscriberInfo implements PagerSubscriber{

  static final long serialVersionUID = 1L;

  private String coverageRegionCode;
  private String capCode;
  private Date nextPhoneNumberChangeDate;
  private String nextPhoneNumber;

  public String getCapCode(){
    return capCode;
  }

  public void setCapCode(String capCode){
    this.capCode = capCode;
  }

  public String getCoverageRegionCode(){
    return coverageRegionCode;
  }

  public void setCoverageRegionCode(String code){
    this.coverageRegionCode = code;
  }

  public boolean isIDEN() {
    return false;
  }

  public boolean isPCS() {
    return false;
  }

  public boolean isPager() {
    return true;
  }

  public void sendTestPage() throws TelusAPIException{
    throw new UnsupportedOperationException("Method not implemented here");
  }

  public Equipment[] getSecondaryEquipments() throws TelusAPIException {
    throw new UnsupportedOperationException("Method not implemented here.");
  }

  public PagerEquipment newNetworkPagerEquipment(String capCode) {
    throw new UnsupportedOperationException("Method not implemented here.");
  }

  public void changeEquipment(PagerEquipment newEquipment, PagerEquipment[] newSecondaryEquipments, String dealerCode, String salesRepCode, String requestorId, boolean ignoreSerialNoInUse) throws  TelusAPIException, SerialNumberInUseException, InvalidEquipmentChangeException, InvalidPagerEquipmentException {
    throw new UnsupportedOperationException("Method not implemented here.");
  }

  public void testChangeEquipment(PagerEquipment newEquipment, PagerEquipment[] newSecondaryEquipments, String dealerCode, String salesRepCode, String requestorId, boolean ignoreSerialNoInUse) throws TelusAPIException, SerialNumberInUseException, InvalidEquipmentChangeException, InvalidPagerEquipmentException {
    throw new UnsupportedOperationException("Method not implemented here.");
  }

  public void setNextPhoneNumberChangeDate(Date nextPhoneNumberChangeDate) {
    this.nextPhoneNumberChangeDate = nextPhoneNumberChangeDate;
  }

  public Date getNextPhoneNumberChangeDate() {
    return nextPhoneNumberChangeDate;
  }

  public void setNextPhoneNumber(String nextPhoneNumber) {
    this.nextPhoneNumber = nextPhoneNumber;
  }

  public String getNextPhoneNumber() {
    return nextPhoneNumber;
  }
  
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("PagerSubscriberInfo[");
		buffer.append("capCode = ").append(capCode);
		buffer.append(" coverageRegionCode = ").append(coverageRegionCode);
		buffer.append(" nextPhoneNumber = ").append(nextPhoneNumber);
		buffer.append(" nextPhoneNumberChangeDate = ").append(
				nextPhoneNumberChangeDate);
		buffer.append("]");
		return buffer.toString();
	}

	public void changeEquipment(PagerEquipment newEquipment, PagerEquipment[] newSecondaryEquipments, String dealerCode, String salesRepCode, String requestorId, char allowDuplicateSerialNo) throws TelusAPIException, SerialNumberInUseException, InvalidEquipmentChangeException, InvalidPagerEquipmentException {
	    throw new UnsupportedOperationException("Method not implemented here.");
	}

	public void testChangeEquipment(PagerEquipment newEquipment, PagerEquipment[] newSecondaryEquipments, String dealerCode, String salesRepCode, String requestorId, char allowDuplicateSerialNo) throws TelusAPIException, SerialNumberInUseException, InvalidEquipmentChangeException, InvalidPagerEquipmentException {
	    throw new UnsupportedOperationException("Method not implemented here.");
	}
}
